"""
diag_cl_correctness.py
----------------------
Correctness checks for the closed-loop validation machinery (D-074).

Check 1  Controller vs MATLAB zpk: our exported+DF2T controller must match
         lsim on the ORIGINAL zpk objects (run make_cl_reference.m first).
Check 2  Perfect-model test: synthetic measurement generated by closed-loop
         simulation of the FP model itself; evaluating the SAME model against
         it must give (a) machine-zero error with identical x0 (loop
         determinism / plumbing) and (b) small NRMSE with the x0 rebuilt from
         the synthetic measurement the way _post_eval_cl does.
Check 3  Open-loop / closed-loop consistency: replaying the total force
         recorded from the closed-loop run through the open-loop simulator
         must reproduce the same positions.
Check 4  Timing convention: lag scan of the controller replay against the
         logged MF230 (expected best lag = 0, i.e. no computational delay).
Check 5  Sanity: pole radii / DC / HF gain of all six controllers, replay
         consistency on iterETEL and on a validation operating point,
         current-limit headroom of the logged data.

Run:
    conda run -n GraduationProject python scripts/gantry/real-data-verification/diag_cl_correctness.py
"""

__project_origin__ = "added"

import os
import sys
import numpy as np
import torch
from scipy.io import loadmat

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.normpath(os.path.join(_HERE, '..', '..', '..'))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import run_telica_param_recovery as rt          # reuses the evaluator under test
from telica_controller import TelicaFeedbackController, _load_ba
from telica_loader import load_telica_log_cl, _A_TO_N

_SAVE_DIR = os.path.join(_ROOT, 'simulations', 'gantry_subnet',
                         'diagnostics', 'cl_correctness')
_ITER0 = os.path.join(_ROOT, 'kamtin-data', 'Data Telica',
                      '06 40 mm XL 80 mm YL', 'train', 'xpos_-60_ypos-40',
                      'iter0.log')
_ITERETEL = os.path.join(os.path.dirname(_ITER0), 'iterETEL.log')
_VAL_ITER0 = os.path.join(_ROOT, 'kamtin-data', 'Data Telica',
                          '06 40 mm XL 80 mm YL', 'validation',
                          'xpos_-135_ypos120', 'iter0.log')

PASS = lambda ok: 'PASS' if ok else 'FAIL'


def check1_matlab_reference():
    print('\n--- Check 1: controller vs MATLAB (original zpk) ---')
    ref_path = os.path.join(_SAVE_DIR, 'matlab_reference.mat')
    if not os.path.isfile(ref_path):
        print('  matlab_reference.mat not found. Run first:')
        print('  matlab -batch "run(\'scripts/gantry/real-data-verification/make_cl_reference.m\')"')
        return None
    m = loadmat(ref_path, squeeze_me=True)
    e, y_ref = np.atleast_2d(m['e']), np.atleast_2d(m['y_ref'])
    y_ref_tf = np.atleast_2d(m['y_ref_tf'])
    ctrl = TelicaFeedbackController()
    y_py = ctrl.filt(e)
    # pass criterion: identical arithmetic path (tfdata + filter) must agree
    rel_tf = np.abs(y_py - y_ref_tf).max() / np.abs(y_ref_tf).max()
    ok = rel_tf < 1e-10
    print(f'  vs MATLAB filter(tfdata)  : max rel dev = {rel_tf:.3e}   '
          f'{PASS(ok)}  (threshold 1e-10, same arithmetic path)')
    # informational: deviation from lsim = tf-form conditioning, not a bug
    rel_ss = np.abs(y_py - y_ref).max() / np.abs(y_ref).max()
    ml_int = np.abs(y_ref_tf - y_ref).max() / np.abs(y_ref).max()
    print(f'  vs MATLAB lsim (ss path)  : max rel dev = {rel_ss:.3e}   '
          f'(info: MATLAB-internal tf-vs-ss = {ml_int:.3e}; '
          f'difference is polynomial-form conditioning of the unit-circle poles)')
    return ok


class _ScaledController(TelicaFeedbackController):
    """Gain-scaled controller for the perfect-model test only.

    The real controller destabilizes the plant-mismatched Kamtin-parameter
    model (smoke test, D-074), and in an unstable loop the rebuilt-x0 test is
    meaningless: initial-state differences grow exponentially. A weak (scaled)
    controller keeps the loop stable while exercising the exact same
    evaluator plumbing.
    """

    def __init__(self, scale):
        super().__init__()
        self._scale = float(scale)

    def step(self, e_m):
        return super().step(e_m) * self._scale


def check2_and_3_perfect_model():
    print('\n--- Check 2: perfect-model closed-loop test (scaled controller) ---')
    dtype = rt.tr.DTYPE
    blk = rt._lfr_pb.ParameterizedLFRBlock(RMSE_baseline=1.0).to(dtype=dtype)
    d = load_telica_log_cl(_ITER0, dtype=dtype)
    r = d['r']
    T = r.shape[0]
    u_ff0 = torch.zeros(T, 3, dtype=dtype)
    ts_tensor = torch.tensor(float(rt._ts), dtype=dtype)
    SCALE = 0.02   # HEURISTIC: weak enough for a stable loop on the mismatched model

    x0_gen = rt._build_state_traj_logical(
        d['q1'][:2], rt._P.to(dtype), float(rt._ts), dtype)[:1]

    # (gen) synthetic measurement from the model in closed loop
    y_syn, i_syn = rt._run_closed_loop(
        blk, x0_gen, r, u_ff0, _ScaledController(SCALE), ts_tensor, dtype)

    # (2a) identical x0: loop must be deterministic to machine precision
    y_rep, _ = rt._run_closed_loop(
        blk, x0_gen, r, u_ff0, _ScaledController(SCALE), ts_tensor, dtype)
    rel_a = float((y_rep - y_syn).abs().max() / y_syn.abs().max())
    ok_a = rel_a < 1e-12
    print(f'  (2a) same-x0 repeat: max rel dev = {rel_a:.3e}   {PASS(ok_a)}  (threshold 1e-12)')

    # (2b) x0 rebuilt from the synthetic measurement, as _post_eval_cl does
    x0_eval = rt._build_state_traj_logical(
        y_syn[:2], rt._P.to(dtype), float(rt._ts), dtype)[:1]
    y_eval, _ = rt._run_closed_loop(
        blk, x0_eval, r, u_ff0, _ScaledController(SCALE), ts_tensor, dtype)
    diff = y_eval - y_syn
    nrmse = (diff.pow(2).mean(0).sqrt()
             / y_syn.std(0).clamp(min=1e-12) * 100.0)
    # HEURISTIC threshold 1%: only the finite-difference x0 velocity error
    # remains, and the feedback suppresses it.
    ok_b = bool((nrmse < 1.0).all())
    print(f'  (2b) rebuilt-x0 eval: NRMSE per axis [%] = '
          f'{nrmse[0]:.4f}  {nrmse[1]:.4f}  {nrmse[2]:.4f}   {PASS(ok_b)}  (threshold 1%)')

    fig, axs = plt.subplots(3, 1, figsize=(11, 7), sharex=True)
    t = np.arange(T) / d['fs']
    for i, lbl in enumerate(['X1', 'X2', 'Y']):
        axs[i].plot(t, diff[:, i].numpy(), lw=0.7)
        axs[i].set_ylabel(f'{lbl} resid [m]')
        axs[i].grid(alpha=0.3)
        axs[i].set_title(f'{lbl}: NRMSE = {float(nrmse[i]):.4f} %', fontsize=9)
    axs[-1].set_xlabel('time [s]')
    fig.suptitle('Perfect-model test: evaluator residual when the model IS the plant\n'
                 '(only the rebuilt-x0 transient may remain)')
    fig.tight_layout()
    fp = os.path.join(_SAVE_DIR, 'perfect_model_residual.png')
    fig.savefig(fp, dpi=150)
    plt.close(fig)
    print(f'  figure -> {os.path.relpath(fp, _ROOT)}')

    print('\n--- Check 3: open-loop replay of the closed-loop force ---')
    a_to_n = torch.tensor(_A_TO_N, dtype=dtype)
    u_total = (i_syn * a_to_n + u_ff0).unsqueeze(0)      # (1, T, 3) stage force
    res_ol = rt._run_no_grad(blk, x0_gen, u_total, ts_tensor)
    y_ol = res_ol.Y[0]
    rel_3 = float((y_ol - y_syn).abs().max() / y_syn.abs().max())
    ok_3 = rel_3 < 1e-10
    print(f'  max rel dev OL vs CL positions = {rel_3:.3e}   {PASS(ok_3)}  (threshold 1e-10)')
    return ok_a and ok_b, ok_3


def check4_lag_scan():
    """
    Timing analysis (informational). Two possible outcomes:
      - sharp peak at a small lag (1-3 samples): real DSP pipeline delay,
        should then be added to the closed-loop simulation;
      - broad maximum at a large lag: logging-path artifact (M2 and MF230
        recorded at different pipeline points). A large delay cannot be
        inside the real loop: at ~300 Hz crossover, 2.5 ms would cost ~270
        degrees of phase and the machine would be unstable, which it is not.
        In that case the zero-delay loop in _run_closed_loop is correct.
    Measured result (2026-07-03): broad maximum at ~+50 samples (~2.5 ms),
    corr 0.972 (lag 0) -> 0.992 (lag +50) -> falling by +80. Conclusion:
    logging-path lag, keep the zero-delay loop.
    """
    print('\n--- Check 4: timing analysis (informational) ---')
    d = load_telica_log_cl(_ITER0)
    e = (d['r'] - d['q1']).numpy()
    i_log = d['i_fb'].numpy()
    ctrl = TelicaFeedbackController()
    i_rep = ctrl.filt(e)
    for i, lbl in enumerate(['X1', 'X2', 'Y']):
        corrs = {}
        for lag in range(-10, 81):
            if lag >= 0:
                a, b = i_rep[:len(i_rep) - lag or None, i], i_log[lag:, i]
            else:
                a, b = i_rep[-lag:, i], i_log[:lag, i]
            corrs[lag] = float(np.corrcoef(a, b)[0, 1])
        best = max(corrs, key=corrs.get)
        kind = ('sharp small-lag peak -> add pipeline delay to the loop'
                if 0 <= best <= 3 else
                'broad large-lag maximum -> logging-path artifact, keep zero-delay loop')
        print(f'  {lbl}: corr(0) = {corrs[0]:.4f}, max corr = {corrs[best]:.4f} '
              f'at lag {best:+d} ({best * 50} us)')
        print(f'      verdict: {kind}')
    return None   # informational: excluded from the pass/fail summary


def check5_sanity():
    print('\n--- Check 5: controller and data sanity ---')
    ba, Ts = _load_ba()
    # authoritative pole moduli from the original zpk (make_cl_reference.m);
    # np.roots on the ill-conditioned tf polynomials wobbles unit-circle
    # (integrator) poles by ~1e-6 and is NOT used as the criterion.
    ref_path = os.path.join(_SAVE_DIR, 'matlab_reference.mat')
    pole_ref = None
    if os.path.isfile(ref_path):
        m = loadmat(ref_path, squeeze_me=True)
        if 'pole_mod_max' in m:
            pole_ref = np.asarray(m['pole_mod_max'], float).ravel()
    ok_stable = True
    print('  controller poles / gains (pole moduli from original zpk):')
    for row, (name, (b, a)) in enumerate(ba.items()):
        if pole_ref is not None:
            pmax = float(pole_ref[row])
            src = 'zpk'
        else:
            pmax = float(np.abs(np.roots(a)).max()) if len(a) > 1 else 0.0
            src = 'roots(a) fallback'
        dc = float(np.sum(b) / np.sum(a)) if abs(np.sum(a)) > 1e-15 else np.inf
        w = np.pi
        hf = float(np.abs(np.polyval(b[::-1], np.exp(-1j * w))
                          / np.polyval(a[::-1], np.exp(-1j * w))))
        # integrator poles at |z| = 1 are by design (marginal, not unstable);
        # the zpk stores them with ~1e-7 rounding, so tolerance 1e-6. Growth
        # over one 0.44 s trajectory: (1 + 6e-8)^8800 ~ 1.0005 -- harmless.
        stable = pmax <= 1.0 + 1e-6
        ok_stable &= stable
        print(f'    {name:4s}: max|pole| = {pmax:.9f} ({src})  {PASS(stable)}   '
              f'DC = {dc:10.4g} A/m   HF(Nyq) = {hf:10.4g} A/m')

    print('  replay consistency across files/positions (corr, LS scale):')
    ctrl = TelicaFeedbackController()
    for tag, path in (('iter0    train(-60,-40) ', _ITER0),
                      ('iterETEL train(-60,-40) ', _ITERETEL),
                      ('iter0    val(-135,+120) ', _VAL_ITER0)):
        if not os.path.isfile(path):
            print(f'    {tag}: file missing, skipped')
            continue
        d = load_telica_log_cl(path)
        e = (d['r'] - d['q1']).numpy()
        i_log = d['i_fb'].numpy()
        ctrl.reset()
        i_rep = ctrl.filt(e)
        stats = []
        for i in range(3):
            c = float(np.corrcoef(i_rep[:, i], i_log[:, i])[0, 1])
            s = float(np.dot(i_rep[:, i], i_log[:, i]) / np.dot(i_rep[:, i], i_rep[:, i]))
            stats.append(f'{c:.3f}/{s:.2f}')
        imax = float(np.abs(i_log).max())
        print(f'    {tag}: X1 {stats[0]}  X2 {stats[1]}  Y {stats[2]}   '
              f'max|MF230| = {imax:.2f} A')
    print('  current limits (Telica 1.mat): peak 27.9 A, continuous ~9.0 A;')
    print('  logged currents stay well below peak -> no saturation modeling needed.')
    return ok_stable


if __name__ == '__main__':
    os.makedirs(_SAVE_DIR, exist_ok=True)
    print('=' * 74)
    print('CLOSED-LOOP MACHINERY CORRECTNESS CHECKS (D-074)')
    print('=' * 74)
    r1 = check1_matlab_reference()
    r5 = check5_sanity()
    r4 = check4_lag_scan()
    r2, r3 = check2_and_3_perfect_model()

    print('\n' + '=' * 74)
    print('SUMMARY')
    print('=' * 74)
    print(f'  1 controller vs MATLAB zpk : {"SKIPPED" if r1 is None else PASS(r1)}')
    print(f'  2 perfect-model evaluator  : {PASS(r2)}')
    print(f'  3 OL/CL consistency        : {PASS(r3)}')
    print(f'  4 timing analysis          : informational (see verdict above)')
    print(f'  5 controller stability     : {PASS(r5)}')
