"""
step1_baseline_equals_system.py
-------------------------------
Encoder verification Step 1: baseline = system (no MSD).

The .mat data (USE_MSD=false) is generated by the MATLAB FP model, which IS
the baseline system. There is zero plant-model mismatch, so after training
the encoder should reconstruct states with NRMS ~1e-5 (noise floor).
Jan: "cant imagine it jumps so high from e^-5."

Both the trained encoder and the analytical baseline (P_inv + finite-diff)
are compared against x_logical from .mat files (ground truth).

Structure follows Jan's interconnect_fit.py (scripts/gantry/encoder_initialisation/).

Usage:
    conda run -n GraduationProject python scripts/gantry/encoder/step1_baseline_equals_system.py
"""

import os
import sys
import json
import numpy as np
import torch
import deepSI
from scipy.io import loadmat
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# --- Project root ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, '..', '..', '..'))
sys.path.insert(0, PROJECT_ROOT)

from model_augmentation.utils.utils import (
    normalize_linear_ss_matrices, selection_matrix, expansion_matrix,
)
from model_augmentation.utils.torch_nets import (
    zero_init_feed_forward_nn, LinearInitEncoderWrapper,
)
from model_augmentation.fit_systems.interconnect import Interconnect, SSE_Interconnect
from model_augmentation.fit_systems.blocks import (
    Gantry_State_Block, Linear_Output_Block, Static_ANN_Block,
)
from model_augmentation.fit_systems.pre_encoder import linear_encoder_init
from model_augmentation.systems.gantry_ss import Cd, Dd, P
from model_augmentation.systems.gantry_linearization import gantry_linearize_and_discretize

# =============================================================================
# Configuration
# =============================================================================

NX_PHYS = 6
nu = 3
ny = 3
Y_OP = None  # LPV self-scheduled

FS_ORIG = 20000
FS_NEW = 400  # HEURISTIC: 10x lower than original 4 kHz; update after downsampling validation
D = FS_ORIG // FS_NEW
TS_NEW = 1.0 / FS_NEW

DTYPE_NP = np.float32
DTYPE_PT = torch.float32

SEED = 42

# Encoder evaluation method: 'direct' = sliding-window batch forward pass (pure encoder
# quality, no model propagation error). 'apply_experiment' = full simulation from t=0
# (encoder + model, errors compound). Direct matches the diagnostic script.
EVAL_METHOD = 'direct'

# HEURISTIC: Jan's rule of thumb for encoder history length
na = 4 * NX_PHYS + 1  # = 25
nb = na
na_right = 1  # required by linear_encoder_init (reconstructability needs y(k))
nb_right = 1

# Window sizes seen by encoder.forward()
_NB_WIN    = nb + nb_right    # 26
_NA_WIN    = na + na_right    # 26
_WIN_START = max(_NB_WIN, _NA_WIN) - 1  # = 25  (first valid timestep)

# Training hyperparameters
HP = dict(
    NX_ANN=0,              # no augmented states: baseline = system
    n_nodes_per_layer=16,
    n_hidden_layers=2,
    up_sample=1,           # validated: downsampling Test B, up_sample=1 sufficient at 400 Hz
    nf=20,                 # HEURISTIC: Jan's rule ~0.1s/Ts = 40; nf=20 validated BETTER in diagnostic
    batch_size=128,        # HEURISTIC: Jan: "take less number of batch sizes"
    lr=1e-4,               # validated: diagnostic_nf_lr_400hz.py nf=20 lr=1e-4 → BETTER (0.70x)
    epochs=100,
)

# Data (baseline-v2: oscillatory + repeated p2p, 10s trajectories, f_high=7 Hz)
TRAJ_DIR = os.path.join(PROJECT_ROOT, 'data', 'gantry', 'matlab', 'multisine', 'baseline-v2')

TRAIN_FILES = [
    'T1_Y_osc.mat',
    'T2_X_sym_Y_sweep.mat',
    'T3_X_sym_Y000.mat',
    'T4_X_sym_Y030.mat',
    'T5_theta_Y_coupling.mat',
    'T6_lissajous_XY.mat',
    'T7_full_MIMO.mat',
    'T8_multi_amp.mat',
    'T9_Y_sweep_repeated.mat',
    'T10_multi_axis_repeated.mat',
]
VAL_FILES = ['V1_osc_Y025.mat', 'V2_p2p_Y020.mat']

# Output
OUT_DIR = os.path.join(PROJECT_ROOT, 'simulations', 'gantry_subnet', 'encoder')
os.makedirs(OUT_DIR, exist_ok=True)

STATE_NAMES = ['q1', 'q2', 'q3', 'dq1', 'dq2', 'dq3']
PHYS_UNITS = ['m', 'm', 'm', 'm/s', 'm/s', 'm/s']


def compute_rms_error(x_hat, x_target):
    """Per-channel RMS error (same units as input)."""
    return np.sqrt(np.mean((x_hat - x_target)**2, axis=0))

# =============================================================================
# Data loading (uses .mat data directly, no FP re-simulation needed)
# =============================================================================

np.random.seed(SEED)
torch.manual_seed(SEED)


def load_mat(filename):
    """Load u, y, x_logical from .mat file, downsample to FS_NEW."""
    d = loadmat(os.path.join(TRAJ_DIR, filename), squeeze_me=True)
    u = d['u_total'][::D].astype(DTYPE_NP) if 'u_total' in d else d['u'][::D].astype(DTYPE_NP)
    y = d['y'][::D].astype(DTYPE_NP)
    x_logical = d['x_logical'][::D].astype(DTYPE_NP)
    return u, y, x_logical


# =============================================================================
# Normalization (from x_logical, same as step0)
# =============================================================================

def compute_normalization(train_data):
    """Compute normalization constants from training data using x_logical."""
    u_all = np.concatenate([u for u, _, _ in train_data])
    y_all = np.concatenate([y for _, y, _ in train_data])
    x_all = np.concatenate([x for _, _, x in train_data])

    x_mean = x_all.mean(axis=0).reshape(NX_PHYS, 1).astype(DTYPE_NP)
    std_x = x_all.std(axis=0).reshape(NX_PHYS, 1).astype(DTYPE_NP) + 1e-8
    std_u = u_all.std(axis=0).reshape(nu, 1).astype(DTYPE_NP) + 1e-8
    u_mean = u_all.mean(axis=0).reshape(nu, 1).astype(DTYPE_NP)
    ystd = y_all.std(axis=0).astype(DTYPE_NP) + 1e-8
    y0 = (Cd.numpy() @ x_mean.flatten()).astype(DTYPE_NP)

    return dict(
        x_mean=x_mean, std_x=std_x, std_u=std_u, u_mean=u_mean,
        ystd=ystd, y0=y0,
        u_all=u_all, y_all=y_all, x_all=x_all,
    )


# =============================================================================
# Analytical baseline (P_inv + finite-diff)
# =============================================================================

def compute_analytical_baseline(y, x_logical, norm):
    """Analytical state estimates: P_inv for positions, backward FD for velocities.

    Returns per-channel NRMS against x_logical (un-normalized, physical units).
    """
    P_inv_T = np.linalg.inv(P.numpy().T).astype(DTYPE_NP)

    # THEORY: q_logical = P_inv @ y_stage (measurement equation)
    pos = (P_inv_T @ y.T).T  # (N, 3)

    # HEURISTIC: backward finite difference for velocity, O(Ts) accurate
    vel = np.zeros_like(pos)
    vel[1:] = (pos[1:] - pos[:-1]) * FS_NEW
    vel[0] = vel[1]

    x_analytical = np.hstack([pos, vel])  # (N, 6)

    # Per-channel NRMS vs x_logical
    err = x_analytical - x_logical
    rms_err = np.sqrt(np.mean(err**2, axis=0))
    rms_gt = np.sqrt(np.mean(x_logical**2, axis=0))
    nrms = rms_err / (rms_gt + 1e-12)

    return nrms, x_analytical


# =============================================================================
# Build model (mirrors gantry_interconnect_dynamic.py:build_model)
# =============================================================================

def build_model(hp, norm):
    """Build interconnect + SSE_Interconnect with linear_encoder_init."""
    NX_ANN = hp['NX_ANN']
    nxd = NX_PHYS + NX_ANN

    x_mean = norm['x_mean']
    std_x = norm['std_x']
    std_u = norm['std_u']
    u_mean = norm['u_mean']
    ystd = norm['ystd']
    y0 = norm['y0']

    Cd_norm = Cd.numpy() * std_x.flatten()[None, :] / ystd[:, None]
    Dd_np = Dd.numpy()

    PHY_IX = np.arange(NX_PHYS)

    ic = Interconnect(nxd, nu, ny, debugging=False)

    phy_block = Gantry_State_Block(
        Y_op=Y_OP, std_x=std_x, std_u=std_u,
        x_mean=x_mean, u_mean=u_mean, Ts=TS_NEW,
        up_sample=hp['up_sample'],
    ).to(DTYPE_PT)
    out_block = Linear_Output_Block(C=Cd_norm, D=Dd_np)
    ic.add_block(phy_block)
    ic.add_block(out_block)

    ann_block = Static_ANN_Block(
        nz=nxd + nu, nw=nxd,
        n_nodes_per_layer=hp['n_nodes_per_layer'],
        n_hidden_layers=hp['n_hidden_layers'],
        net=zero_init_feed_forward_nn,
        activation=torch.nn.Tanh,
    )
    ic.add_block(ann_block)

    # Freeze ANN block: baseline = system means zero mismatch, so ANN
    # correction must stay at zero.  Without freezing, the encoder and ANN
    # co-adapt to a non-physical state representation (output loss drops
    # but internal states diverge from ground truth).
    if NX_ANN == 0:
        for p in ann_block.parameters():
            p.requires_grad = False

    ic.connect_block_signals(ann_block, ["x", "u"], ["xp"])
    ic.connect_signals("x", phy_block, "concat", selection_matrix(PHY_IX, nxd))
    ic.connect_block_signals(phy_block, ["u"], [])
    ic.connect_signals(phy_block, "xp", "additive", expansion_matrix(PHY_IX, nxd))
    ic.connect_signals("x", out_block, "concat", selection_matrix(PHY_IX, nxd))
    ic.connect_block_signals(out_block, ["u"], ["y"])

    fit_sys = SSE_Interconnect(
        interconnect=ic, na=na, nb=nb,
        na_right=na_right, nb_right=nb_right,
        e_net_kwargs={
            "n_nodes_per_layer": hp['n_nodes_per_layer'],
            "n_hidden_layers": hp['n_hidden_layers'],
        },
    )

    # Manual normalization
    fit_sys.norm.u0 = u_mean.flatten()
    fit_sys.norm.ustd = std_u.flatten()
    fit_sys.norm.y0 = y0
    fit_sys.norm.ystd = ystd

    # --- Encoder: linear_encoder_init (Hoekstra 2026 Eq. 16-17) ---
    Ad, Bd, Cd_dt, Dd_dt = gantry_linearize_and_discretize(dt=TS_NEW)

    sys_data_with_x = deepSI.System_data(u=norm['u_all'], y=norm['y_all'])
    sys_data_with_x.x = norm['x_all']

    Ad_bar, Bd_bar, Cd_bar, Dd_bar = normalize_linear_ss_matrices(
        Ad, Bd, Cd_dt, Dd_dt, sys_data_with_x)

    phys_encoder = linear_encoder_init(
        A=Ad_bar, B=Bd_bar, C=Cd_bar, D=Dd_bar,
        nx=NX_PHYS, nu=nu, ny=ny, na=na, nb=nb,
        n_nodes_per_layer=hp['n_nodes_per_layer'],
        n_hidden_layers=hp['n_hidden_layers'],
        flag_linear_only=False,
    )

    fit_sys.encoder = LinearInitEncoderWrapper(
        phys_encoder=phys_encoder,
        nx_ann=NX_ANN,
        nb=nb + nb_right, nu=nu, na=na + na_right, ny=ny,
        n_nodes_per_layer=hp['n_nodes_per_layer'],
        n_hidden_layers=hp['n_hidden_layers'],
        u_mean=u_mean, std_u=std_u, y0=y0, ystd=ystd,
        x_mean=x_mean, std_x=std_x,
    ).to(DTYPE_PT)

    return fit_sys


# =============================================================================
# Evaluate encoder states via saved_output_signals
# =============================================================================

def evaluate_encoder_states(fit_sys, val_sys_data, x_logical_val, norm):
    """Run apply_experiment, extract evolved states, compare to x_logical.

    Returns per-channel NRMS in physical units (un-normalized).
    """
    x_mean = norm['x_mean']
    std_x = norm['std_x']

    fit_sys.eval()
    fit_sys.hfn.reset_saved_signals()
    sim_result = fit_sys.apply_experiment(val_sys_data)
    cheat_n = sim_result.cheat_n

    # saved_output_signals: (total_dim, T), first NX_PHYS rows = normalized states
    x_enc_norm = np.array(fit_sys.hfn.saved_output_signals)[:NX_PHYS, :]  # (6, T)
    x_enc_phys = (x_enc_norm * std_x + x_mean).T  # (T, 6)

    # Align with ground truth (skip cheat_n initial samples)
    x_gt = x_logical_val[cheat_n:]
    T = min(len(x_enc_phys), len(x_gt))
    x_enc_phys = x_enc_phys[:T]
    x_gt = x_gt[:T]

    # Per-channel NRMS
    err = x_enc_phys - x_gt
    rms_err = np.sqrt(np.mean(err**2, axis=0))
    rms_gt = np.sqrt(np.mean(x_gt**2, axis=0))
    nrms = rms_err / (rms_gt + 1e-12)

    return nrms, x_enc_phys, x_gt, cheat_n


# =============================================================================
# Encoder quality evaluation -- direct forward pass, no simulation
# =============================================================================

def evaluate_encoder_direct(fit_sys, val_u, val_y, val_x_logical, norm):
    """Evaluate encoder quality via direct sliding-window forward pass.

    No model simulation — isolates encoder quality from model propagation.
    Matches the evaluation method used in diagnostic_nf_lr_400hz.py.

    Returns: nrms (NX_PHYS,), x_enc_phys (T, NX_PHYS), x_gt (T, NX_PHYS), win_start (int)
    """
    u_mean = norm['u_mean'].flatten()
    std_u  = norm['std_u'].flatten()
    y0     = norm['y0']
    ystd   = norm['ystd']
    x_mean = norm['x_mean'].flatten()
    std_x  = norm['std_x'].flatten()

    u_norm = (val_u - u_mean) / std_u
    y_norm = (val_y - y0) / ystd

    u_wins = np.lib.stride_tricks.sliding_window_view(
        u_norm, (_NB_WIN, nu)).reshape(-1, _NB_WIN, nu)
    y_wins = np.lib.stride_tricks.sliding_window_view(
        y_norm, (_NA_WIN, ny)).reshape(-1, _NA_WIN, ny)

    u_batch = torch.tensor(u_wins.copy(), dtype=DTYPE_PT)
    y_batch = torch.tensor(y_wins.copy(), dtype=DTYPE_PT)

    fit_sys.encoder.eval()
    with torch.no_grad():
        x_enc = fit_sys.encoder(u_batch, y_batch).numpy()

    x_phys = x_enc * std_x + x_mean
    x_gt   = val_x_logical[_WIN_START:]
    T = min(len(x_phys), len(x_gt))
    x_phys = x_phys[:T]
    x_gt   = x_gt[:T]

    rms_err = np.sqrt(np.mean((x_phys - x_gt) ** 2, axis=0))
    rms_gt  = np.sqrt(np.mean(x_gt ** 2, axis=0))
    nrms    = rms_err / (rms_gt + 1e-12)

    return nrms, x_phys, x_gt, _WIN_START


def _eval_states(fit_sys, val_u, val_y, val_x_logical, val_sys_data, norm):
    """Dispatch to EVAL_METHOD."""
    if EVAL_METHOD == 'direct':
        return evaluate_encoder_direct(fit_sys, val_u, val_y, val_x_logical, norm)
    else:
        return evaluate_encoder_states(fit_sys, val_sys_data, val_x_logical, norm)


# =============================================================================
# Plotting
# =============================================================================

def plot_state_comparison(x_enc, x_ana, x_gt, nrms_enc, nrms_ana, cheat_n,
                          title, out_path):
    """Time-domain: encoder vs analytical vs ground truth."""
    T = min(2000, len(x_enc))
    t = np.arange(T) / FS_NEW + cheat_n / FS_NEW

    fig, axes = plt.subplots(NX_PHYS, 1, figsize=(14, 2.5 * NX_PHYS), sharex=True)
    for i, ax in enumerate(axes):
        ax.plot(t, x_gt[:T, i], 'k-', linewidth=0.8, label='x_logical (ground truth)')
        ax.plot(t, x_enc[:T, i], 'r--', linewidth=0.8,
                label=f'encoder (NRMS={nrms_enc[i]:.2e})')
        ax.plot(t, x_ana[:T, i], 'b:', linewidth=0.8,
                label=f'analytical (NRMS={nrms_ana[i]:.2e})')
        ax.set_ylabel(STATE_NAMES[i])
        ax.legend(loc='upper right', fontsize=7)
        ax.grid(True, alpha=0.3)
    axes[-1].set_xlabel('Time [s]')
    fig.suptitle(title, y=1.01)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {out_path}')


def plot_state_error(x_enc, x_ana, x_gt, cheat_n, title, out_path):
    """Error time series: encoder error vs analytical error."""
    T = min(2000, len(x_enc))
    t = np.arange(T) / FS_NEW + cheat_n / FS_NEW

    fig, axes = plt.subplots(NX_PHYS, 1, figsize=(14, 2.5 * NX_PHYS), sharex=True)
    for i, ax in enumerate(axes):
        err_enc = x_enc[:T, i] - x_gt[:T, i]
        err_ana = x_ana[:T, i] - x_gt[:T, i]
        ax.plot(t, err_enc, 'r-', linewidth=0.6, label='encoder error')
        ax.plot(t, err_ana, 'b-', linewidth=0.6, label='analytical error')
        ax.set_ylabel(f'{STATE_NAMES[i]} [{PHYS_UNITS[i]}]')
        ax.legend(loc='upper right', fontsize=7)
        ax.grid(True, alpha=0.3)
    axes[-1].set_xlabel('Time [s]')
    fig.suptitle(title, y=1.01)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {out_path}')


def plot_nrms_bar(nrms_dict, title, out_path):
    """Bar chart: NRMS per channel for multiple methods."""
    x = np.arange(NX_PHYS)
    n = len(nrms_dict)
    w = 0.8 / n
    colors = ['tab:orange', 'tab:red', 'tab:blue']
    fig, ax = plt.subplots(figsize=(10, 5))
    for j, (label, nrms) in enumerate(nrms_dict.items()):
        ax.bar(x + (j - n/2 + 0.5) * w, nrms, w, label=label, color=colors[j % len(colors)], alpha=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(STATE_NAMES)
    ax.set_ylabel('NRMS')
    ax.set_yscale('log')
    ax.legend()
    ax.grid(True, alpha=0.3, axis='y')
    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {out_path}')


def plot_loss_curves(fit_sys, out_path):
    """Plot training and validation loss curves."""
    fig, ax = plt.subplots(figsize=(10, 5))
    if hasattr(fit_sys, 'Loss_train') and len(fit_sys.Loss_train) > 0:
        ax.plot(fit_sys.Loss_train, label='train')
    if hasattr(fit_sys, 'Loss_val') and len(fit_sys.Loss_val) > 0:
        ax.plot(fit_sys.Loss_val, label='val')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.set_yscale('log')
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_title('Step 1: Training loss')
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {out_path}')


def plot_state_evolution(state_curves, nrms_init, title, out_path):
    """NRMS per state vs epoch, with horizontal init reference line."""
    epochs = list(range(1, len(next(iter(state_curves.values()))) + 1))
    fig, axes = plt.subplots(NX_PHYS, 1, figsize=(10, 2.2 * NX_PHYS), sharex=True)
    for i, (ax, name) in enumerate(zip(axes, STATE_NAMES)):
        ax.plot(epochs, state_curves[name], 'b-o', markersize=3, linewidth=1, label='per epoch')
        ax.axhline(nrms_init[i], color='orange', linestyle='--', linewidth=1, label='init')
        ax.set_ylabel(f'{name} NRMS')
        ax.set_yscale('log')
        ax.legend(fontsize=7, loc='upper right')
        ax.grid(True, alpha=0.3)
    axes[-1].set_xlabel('Epoch')
    fig.suptitle(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'Saved: {out_path}')


# =============================================================================
# Main
# =============================================================================

def main():
    print('=' * 70)
    print('Step 1: Baseline = system (no MSD), converge to noise floor')
    print('=' * 70)
    print(f'  FS_NEW       = {FS_NEW} Hz  (D={D}, Ts={TS_NEW*1000:.2f} ms)')
    print(f'  na / nb      = {na} / {nb}  (encoder history = {na * TS_NEW * 1000:.1f} ms)')
    print(f'  na_right     = {na_right},  nb_right = {nb_right}')
    print(f'  nf           = {HP["nf"]}  ({HP["nf"] * TS_NEW * 1000:.1f} ms prediction horizon)')
    print(f'  lr           = {HP["lr"]:.0e}')
    print(f'  batch_size   = {HP["batch_size"]}')
    print(f'  epochs       = {HP["epochs"]}')
    print(f'  up_sample    = {HP["up_sample"]}')
    print(f'  NX_ANN       = {HP["NX_ANN"]}  (ANN frozen)')
    print(f'  EVAL_METHOD  = {EVAL_METHOD}')

    # --- Load data ---
    print(f'\nLoading data from: {TRAJ_DIR}')
    train_data = [load_mat(f) for f in TRAIN_FILES]
    val_data = [load_mat(f) for f in VAL_FILES]

    for i, (fname, (u, y, x)) in enumerate(zip(TRAIN_FILES, train_data)):
        print(f'  T{i+1} ({fname}): u={u.shape}, y={y.shape}, x={x.shape}')
    for fname, (u, y, x) in zip(VAL_FILES, val_data):
        print(f'  Val ({fname}): u={u.shape}, y={y.shape}, x={x.shape}')

    # --- Normalization ---
    norm = compute_normalization(train_data)
    print(f'\nNormalization:')
    print(f'  std_x = {norm["std_x"].flatten()}')
    print(f'  std_u = {norm["std_u"].flatten()}')

    # --- Analytical baseline (reference, does not change with training) ---
    # Evaluate on first validation file
    val_u, val_y, val_x_logical = val_data[0]
    print(f'\n--- Analytical baseline (P_inv + FD) on {VAL_FILES[0]} ---')
    nrms_ana, x_analytical = compute_analytical_baseline(val_y, val_x_logical, norm)
    rms_ana_phys = compute_rms_error(x_analytical, val_x_logical)
    print(f'  {"State":<6s}  {"NRMS":>12s}  {"RMS err":>12s}  {"Unit":<5s}')
    print(f'  {"-"*6}  {"-"*12}  {"-"*12}  {"-"*5}')
    for i, name in enumerate(STATE_NAMES):
        print(f'  {name:<6s}  {nrms_ana[i]:>12.4e}  {rms_ana_phys[i]:>12.4e}  {PHYS_UNITS[i]:<5s}')

    # --- Build deepSI System_data ---
    train_list = [
        deepSI.System_data(u=u, y=y, dt=TS_NEW)
        for u, y, _ in train_data
    ]
    train_sys_data = deepSI.System_data_list(train_list)
    # Use first val file for deepSI validation during training
    val_sys_data = deepSI.System_data(u=val_u, y=val_y, dt=TS_NEW)

    # --- Build model ---
    print('\nBuilding model...')
    fit_sys = build_model(HP, norm)
    # Pass optimizer_kwargs to init_model, NOT to fit().
    # fit() skips optimizer creation when init_model_done=True,
    # so optimizer_kwargs passed to fit() are silently ignored.
    fit_sys.init_model(
        sys_data=train_sys_data,
        auto_fit_norm=False,
        optimizer_kwargs={'lr': HP['lr']},
    )
    fit_sys.hfn.to(DTYPE_PT)

    n_params = 0
    for item in fit_sys.parameters_with_names.values():
        params = item['params']
        if isinstance(params, torch.nn.Parameter):
            n_params += params.numel()
        else:
            n_params += sum(p.numel() for p in params)
    print(f'Total trainable parameters: {n_params}')

    # --- Evaluate BEFORE training ---
    print(f'\n--- Encoder quality BEFORE training (EVAL_METHOD={EVAL_METHOD}) ---')
    nrms_init, x_enc_init, x_gt_init, cheat_n = _eval_states(
        fit_sys, val_u, val_y, val_x_logical, val_sys_data, norm)
    rms_init_phys = compute_rms_error(x_enc_init, x_gt_init)
    print(f'  {"State":<6s}  {"NRMS":>12s}  {"RMS err":>12s}  {"Unit":<5s}')
    print(f'  {"-"*6}  {"-"*12}  {"-"*12}  {"-"*5}')
    for i, name in enumerate(STATE_NAMES):
        print(f'  {name:<6s}  {nrms_init[i]:>12.4e}  {rms_init_phys[i]:>12.4e}  {PHYS_UNITS[i]:<5s}')

    # --- Train with per-epoch state tracking ---
    # HEURISTIC: validation_measure = nf-step-RMS (Jan's pattern)
    val_measure = f'{HP["nf"]}-step-RMS'

    print(f'\nTraining: {HP["epochs"]} epochs, validation_measure={val_measure}')
    print(f'Per-epoch state tracking via EVAL_METHOD={EVAL_METHOD}')

    hdr = f'{"epoch":>5s} | {"val_loss":>10s}'
    for name in STATE_NAMES:
        hdr += f' | {name:>10s}'
    print('\n' + hdr)
    print('-' * len(hdr))

    # Print init row
    row = f'{"init":>5s} | {"":>10s}'
    for i in range(NX_PHYS):
        row += f' | {nrms_init[i]:>10.3e}'
    print(row, flush=True)

    state_curves = {name: [] for name in STATE_NAMES}

    for epoch in range(1, HP['epochs'] + 1):
        fit_sys.fit(
            train_sys_data=train_sys_data,
            val_sys_data=val_sys_data,
            batch_size=HP['batch_size'],
            epochs=epoch,
            auto_fit_norm=False,
            loss_kwargs={'nf': HP['nf']},
            validation_measure=val_measure,
            verbose=0,
        )
        ep_loss = float(fit_sys.Loss_val[-1])
        nrms_ep, _, _, _ = _eval_states(fit_sys, val_u, val_y, val_x_logical, val_sys_data, norm)
        for i, name in enumerate(STATE_NAMES):
            state_curves[name].append(float(nrms_ep[i]))
        row = f'{epoch:5d} | {ep_loss:10.4e}'
        for i in range(NX_PHYS):
            row += f' | {nrms_ep[i]:>10.3e}'
        print(row, flush=True)

    # --- Evaluate AFTER training (best checkpoint) ---
    fit_sys.checkpoint_load_system(name='_best')

    for vi, (vf, (vu, vy, vx)) in enumerate(zip(VAL_FILES, val_data)):
        vsd = deepSI.System_data(u=vu, y=vy, dt=TS_NEW)
        print(f'\n--- Encoder quality AFTER training on {vf} ---')
        nrms_post, x_enc_post, x_gt_post, cheat_n = _eval_states(
            fit_sys, vu, vy, vx, vsd, norm)
        rms_post_phys = compute_rms_error(x_enc_post, x_gt_post)
        print(f'  {"State":<6s}  {"NRMS":>12s}  {"RMS err":>12s}  {"Unit":<5s}')
        print(f'  {"-"*6}  {"-"*12}  {"-"*12}  {"-"*5}')
        for i, name in enumerate(STATE_NAMES):
            print(f'  {name:<6s}  {nrms_post[i]:>12.4e}  {rms_post_phys[i]:>12.4e}  {PHYS_UNITS[i]:<5s}')

        # Store first val file results for plots
        if vi == 0:
            nrms_post_v1 = nrms_post
            x_enc_post_v1 = x_enc_post
            x_gt_post_v1 = x_gt_post
            cheat_n_v1 = cheat_n

    # --- Pass/fail (on first val file) ---
    max_nrms_post = np.max(nrms_post_v1)
    max_nrms_ana = np.max(nrms_ana)
    print(f'\nMax NRMS encoder (after training): {max_nrms_post:.4e}')
    print(f'Max NRMS analytical baseline:      {max_nrms_ana:.4e}')

    # HEURISTIC: Jan expects ~1e-5 for baseline=system after training
    if max_nrms_post < 1e-4:
        print('PASS: encoder at noise floor (NRMS < 1e-4)')
    elif max_nrms_post < 1e-3:
        print('MARGINAL: encoder close but not at noise floor (1e-4 to 1e-3)')
        print('Try more epochs or lower lr.')
    else:
        print('FAIL: encoder NRMS too high, investigate pipeline')

    # --- Save results ---
    nrms_post = nrms_post_v1
    x_enc_post = x_enc_post_v1
    x_gt_post = x_gt_post_v1
    cheat_n = cheat_n_v1

    results = dict(
        hp=HP,
        cheat_n=int(cheat_n),
        n_params=n_params,
        nrms_init={name: float(nrms_init[i]) for i, name in enumerate(STATE_NAMES)},
        nrms_post={name: float(nrms_post[i]) for i, name in enumerate(STATE_NAMES)},
        nrms_analytical={name: float(nrms_ana[i]) for i, name in enumerate(STATE_NAMES)},
        loss_train=getattr(fit_sys, 'Loss_train', np.array([])).tolist(),
        loss_val=getattr(fit_sys, 'Loss_val', np.array([])).tolist(),
        state_curves=state_curves,
    )
    json_path = os.path.join(OUT_DIR, 'step1_results.json')
    with open(json_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f'\nSaved: {json_path}')

    # Align analytical baseline to same time window as encoder (skip cheat_n)
    x_ana_aligned = x_analytical[cheat_n:]
    T = min(len(x_enc_post), len(x_ana_aligned))
    x_ana_aligned = x_ana_aligned[:T]

    # Save trajectories for plot reconstruction
    npz_path = os.path.join(OUT_DIR, 'step1_data.npz')
    np.savez_compressed(npz_path,
        x_enc_init=x_enc_init, x_enc_post=x_enc_post,
        x_analytical=x_ana_aligned, x_gt=x_gt_post,
        nrms_init=nrms_init, nrms_post=nrms_post, nrms_analytical=nrms_ana,
        cheat_n=cheat_n, state_names=STATE_NAMES, fs=FS_NEW,
    )
    print(f'Saved: {npz_path}')

    # --- Plots ---
    plot_state_comparison(
        x_enc_init, x_ana_aligned, x_gt_init, nrms_init, nrms_ana, cheat_n,
        'Step 1: BEFORE training (encoder init vs analytical vs ground truth)',
        os.path.join(OUT_DIR, 'step1_before_training.png'))
    plot_state_error(
        x_enc_init, x_ana_aligned, x_gt_init, cheat_n,
        'Step 1: BEFORE training error (physical units)',
        os.path.join(OUT_DIR, 'step1_before_error.png'))

    plot_state_comparison(
        x_enc_post, x_ana_aligned, x_gt_post, nrms_post, nrms_ana, cheat_n,
        'Step 1: AFTER training (encoder vs analytical vs ground truth)',
        os.path.join(OUT_DIR, 'step1_after_training.png'))
    plot_state_error(
        x_enc_post, x_ana_aligned, x_gt_post, cheat_n,
        'Step 1: AFTER training error (physical units)',
        os.path.join(OUT_DIR, 'step1_after_error.png'))

    plot_nrms_bar(
        {'init': nrms_init, 'after training': nrms_post, 'analytical': nrms_ana},
        'Step 1: NRMS per channel (before/after/analytical)',
        os.path.join(OUT_DIR, 'step1_nrms_bar.png'))

    plot_loss_curves(fit_sys, os.path.join(OUT_DIR, 'step1_loss.png'))

    plot_state_evolution(
        state_curves, nrms_init,
        f'Step 1: State NRMS per epoch (EVAL_METHOD={EVAL_METHOD})',
        os.path.join(OUT_DIR, 'step1_state_evolution.png'))


if __name__ == '__main__':
    main()
