"""The recovery floor: how much of the missing physics looks like a parameter change.

THE QUESTION (gap P7). The truth is 8-state (hidden MSD absorber); the baseline is
6-state. Let Delta_true be what the truth does that the baseline cannot, at the TRUE
parameters. Whatever part of Delta_true lies inside span(Phi) cannot live in the ANN under
ANY orthogonality scheme, so the data fit hands it to theta. The number

    floor = ||Q^T Delta_true|| / ||Delta_true||

is therefore a lower bound on the parameter error that no orthogonality method can beat.
It is identical on the penalty route and the by-construction route, so it cannot be dodged
by choosing a method. A parameter-recovery claim that does not report it is undefended.

Reference for the mechanism: gyorok2026obc Eq. 8 credits the in-span component of the
learned output to theta; its Theorem 7 gives zero baseline error only under Condition 4,
Phi^T Delta = 0, i.e. exactly floor = 0. Their own p9 concedes their MSD case fails
Condition 4 and calls the deviation "minimal"; ours is a larger violation and the point of
this script is to stop calling it minimal without a number.

SCOPE. This needs the truth, so it is SIMULATION-ONLY and does not extend to Telica. It
certifies the method; it is not part of the shipped pipeline. The real-data substitute is
cross-record parameter consistency.

CONSTRUCTION, matched to the DEPLOYED penalty rather than to step0:
  - Points: data-derived logical states (D-111, `_x_logical_from_data`), K0-trimmed,
    decimated at cfg.orth_point_stride. This is what `orth_penalty._compute` uses. NOTE
    `step0_point_set.py` instead rolls the baseline out, which is the pre-D-111 choice; do
    not use it here or Q and Delta would live on different point sets.
  - Frame: the NORMALISED next-state frame, because `blk.nonlinear_function` consumes and
    produces normalised quantities and Q is built from Jacobians of that output.
  - Rows: `r_phys`, the routed physical rows, stacked sample-major, matching the row order
    `Phi[si*n_r:(si+1)*n_r]` in `orth_penalty._compute`.
  - The truth uses the absorber trajectory from the SAME records at the SAME indices. This
    pairing is only legitimate because the deployed states are data-derived: the data was
    generated by the 8-state truth, so x_phys and x_aug come from one trajectory. It would
    NOT be legitimate against a baseline rollout, which diverges from the truth.

TWO PROJECTORS, because they answer different questions:
  - Q at theta_bar = theta_0 (the detuned value the penalty actually deploys): what OUR
    method credits to theta.
  - Q at theta_true: the intrinsic floor, independent of where we linearise.
The gap between them measures how much the 10% detune moves the answer.

Outputs -> scripts/gantry/orthogonality/code/recovery_floor.json
Run (background, streams):
  PYTHONIOENCODING=utf-8 PYTHONUNBUFFERED=1 conda run --no-capture-output \
    -n GraduationProject python -u scripts/gantry/orthogonality/code/recovery_floor.py
"""
import os
import sys
import json
import time

import numpy as np
import torch

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, '..', '..', '..', '..')))  # repo root
sys.path.insert(0, os.path.abspath(os.path.join(_HERE, '..', '..')))              # scripts/gantry

from gantry_dynamic.config import RunConfig
from gantry_dynamic.data import load_datasets, compute_normalization
from gantry_dynamic import oracle
from gantry_dynamic.orth_penalty import _x_logical_from_data, _make_block
from model_augmentation.systems.gantry_ss import P as _P

_F64 = torch.float64
OUT = os.path.join(_HERE, 'recovery_floor.json')
P_np = _P.numpy().astype(np.float64)

CFG = RunConfig(use_f64=True, snr=None, up_sample=2)


def theta_true_vec(blk_names):
    """True physical parameters, from gantry_ss (the FP ground truth), in block order."""
    from model_augmentation.systems import gantry_ss as G
    return np.array([float(getattr(G, n)) for n in blk_names], dtype=np.float64)


def truth_step(x6_phys, a2, u_stage, ts, up_sample):
    """One RK4 step of the 8-state truth. Returns the next 6 PHYSICAL logical states.

    8-state order (gantrySystemExtended.m): [X, Th, Y, da, dX, dTh, dY, vda].
    """
    x8 = np.array([x6_phys[0], x6_phys[1], x6_phys[2], a2[0],
                   x6_phys[3], x6_phys[4], x6_phys[5], a2[1]], dtype=np.float64)
    u_log = P_np @ np.asarray(u_stage, dtype=np.float64)
    h = ts / up_sample
    x = x8
    for _ in range(up_sample):
        k1 = oracle._deriv(x, u_log)
        k2 = oracle._deriv(x + 0.5 * h * k1, u_log)
        k3 = oracle._deriv(x + 0.5 * h * k2, u_log)
        k4 = oracle._deriv(x + h * k3, u_log)
        x = x + (h / 6.0) * (k1 + 2 * k2 + 2 * k3 + k4)
    return np.array([x[0], x[1], x[2], x[4], x[5], x[6]], dtype=np.float64)


def build_Q(cfg, norm, X_flat, U_flat, sub_ix, r_phys, theta, tag):
    """Rebuild Phi_tilde = [Phi | Gamma] and its Q at the given theta.

    Transcribed from `orth_penalty._compute` so the two cannot drift apart.
    """
    blk = _make_block(cfg, norm, theta)
    theta_t = torch.tensor(theta, dtype=_F64)
    NX = cfg.nx_phys
    n_r = len(r_phys)
    Phi = np.empty((len(sub_ix) * n_r, 14))
    Gam = np.empty((len(sub_ix) * n_r, 1))
    t0 = time.time()
    for si, ix in enumerate(sub_ix):
        x6 = torch.tensor(X_flat[ix], dtype=_F64)
        u3 = torch.tensor(U_flat[ix], dtype=_F64)
        zin = torch.cat([x6.view(1, NX, 1), u3.view(1, 3, 1)], dim=1)
        xn = blk.nonlinear_function(zin).view(NX)
        J = torch.zeros(NX, 14, dtype=_F64)
        for r in range(NX):
            g = torch.autograd.grad(xn[r], blk.log_params, retain_graph=(r < NX - 1))[0]
            J[r] = g
        J_theta = (J / theta_t.view(1, 14)).detach()
        Jr = J_theta[r_phys, :]
        Phi[si * n_r:(si + 1) * n_r, :] = Jr.numpy()
        Gam[si * n_r:(si + 1) * n_r, 0] = (xn.detach()[r_phys] - Jr @ theta_t).numpy()
        if (si + 1) % 500 == 0:
            print(f'  [{tag}] jac {si+1}/{len(sub_ix)} '
                  f'({(si+1)/(time.time()-t0):.1f}/s)', flush=True)
    Phi_t = np.hstack([Phi, Gam])
    Qf, S, _ = np.linalg.svd(Phi_t, full_matrices=False)
    n_keep = int(np.sum(S > CFG.orth_rank_tol * S[0]))
    print(f'  [{tag}] rank {n_keep}, sigma[{n_keep-1}]/sigma[0] = '
          f'{S[n_keep-1]/S[0]:.3e}', flush=True)
    return Qf[:, :n_keep], S, n_keep


def main():
    print('loading data...', flush=True)
    data = load_datasets(CFG)
    norm = compute_normalization(CFG, data)
    K0 = CFG.na_nb
    NX = CFG.nx_phys
    r_phys = [i for i in CFG.ann_route_ix if i < NX]
    n_r = len(r_phys)
    print(f'K0={K0}, routed physical rows={r_phys}, stride={CFG.orth_point_stride}')

    sx = norm.std_x.flatten()
    mx = norm.x_mean.flatten()
    su = norm.std_u.flatten()
    mu = norm.u_mean.flatten()

    # Same trim and record order as orth_penalty._compute, plus the physical
    # quantities and the absorber trajectory the truth step needs.
    # `load_datasets` attaches x_aug only to val/test, so the absorber trajectory for
    # the TRAIN records is loaded from the same .mat files here, in the same order and
    # with the same decimation. Alignment is asserted below rather than assumed.
    from gantry_dynamic.data import TRAIN_FILES, load_mat_aug
    assert len(TRAIN_FILES) == len(data.train_list), (len(TRAIN_FILES),
                                                      len(data.train_list))
    Xp_parts, Us_parts, A_parts = [], [], []
    for f, sd in zip(TRAIN_FILES, data.train_list):
        u_m, _, xlog_m, xaug_m = load_mat_aug(f, CFG)
        n = len(sd.u)
        assert len(u_m) >= n, (f, len(u_m), n)
        # The .mat u must be the same signal load_traj gave us, or the absorber
        # trajectory is not aligned with the states and the whole number is wrong.
        assert np.allclose(u_m[:n], sd.u, atol=1e-9), f'u mismatch on {f}'
        Xp_parts.append(_x_logical_from_data(sd)[K0:].astype(np.float64))
        Us_parts.append(sd.u[K0:].astype(np.float64))
        A_parts.append(xaug_m[:n][K0:].astype(np.float64))
    Xp = np.concatenate(Xp_parts)          # physical logical states
    Us = np.concatenate(Us_parts)          # STAGE forces
    Aa = np.concatenate(A_parts)           # [delta_a, vdelta_a]
    X_flat = (Xp - mx) / sx
    U_flat = (Us - mu) / su
    print(f'samples: {X_flat.shape[0]}, x_aug std = '
          f'{Aa[:,0].std():.3e} m / {Aa[:,1].std():.3e} m/s')

    sub_ix = np.arange(0, X_flat.shape[0], CFG.orth_point_stride)
    print(f'decimated points: {len(sub_ix)}')

    # theta_true is the FP nominal; theta_dep is what the penalty actually deploys,
    # which is `theta_bar_for(cfg)`: nominal times the detune vector under joint
    # estimation. Taking it from that function rather than re-deriving it means the
    # two cannot drift apart.
    from gantry_dynamic.orth_penalty import theta_bar_for
    from model_augmentation.fit_systems.blocks import Parameterized_Gantry_State_Block
    names = Parameterized_Gantry_State_Block.PARAM_NAMES
    theta_true = theta_true_vec(names)
    theta_dep = np.asarray(theta_bar_for(CFG), dtype=np.float64)
    detuned = not np.allclose(theta_dep, theta_true)
    print('theta_true =', np.array2string(theta_true, precision=4))
    print('theta_dep  =', np.array2string(theta_dep, precision=4))
    print(f'detune (%) = {np.array2string(100*(theta_dep/theta_true - 1), precision=2)}'
          f'   [joint_estimation={CFG.joint_estimation}, detuned={detuned}]')

    # ---- Delta_true on the decimated points, normalised frame, routed rows ----
    blk_true = _make_block(CFG, norm, theta_true)
    ts, ups = CFG.ts_new, CFG.up_sample
    D = np.empty((len(sub_ix) * n_r,))
    base_mag = np.empty((len(sub_ix) * n_r,))
    t0 = time.time()
    for si, ix in enumerate(sub_ix):
        x6n = torch.tensor(X_flat[ix], dtype=_F64)
        u3n = torch.tensor(U_flat[ix], dtype=_F64)
        zin = torch.cat([x6n.view(1, NX, 1), u3n.view(1, 3, 1)], dim=1)
        with torch.no_grad():
            xn_base = blk_true.nonlinear_function(zin).view(NX).numpy()   # normalised
        xn_truth_phys = truth_step(Xp[ix], Aa[ix], Us[ix], ts, ups)
        xn_truth = (xn_truth_phys - mx) / sx
        d = (xn_truth - xn_base)[r_phys]
        D[si * n_r:(si + 1) * n_r] = d
        base_mag[si * n_r:(si + 1) * n_r] = xn_base[r_phys]
        if (si + 1) % 1000 == 0:
            print(f'  delta {si+1}/{len(sub_ix)} '
                  f'({(si+1)/(time.time()-t0):.1f}/s)', flush=True)
    nD = float(np.linalg.norm(D))
    print(f'\n||Delta_true|| = {nD:.6e}   (normalised units, {D.size} entries)')
    print(f'relative to next-state magnitude: '
          f'{nD/np.linalg.norm(base_mag):.6e}')

    res = {'n_points': int(len(sub_ix)), 'n_r': n_r, 'r_phys': r_phys,
           'stride': int(CFG.orth_point_stride),
           'norm_Delta': nD,
           'Delta_rel_to_state': float(nD / np.linalg.norm(base_mag)),
           'x_aug_std': [float(Aa[:, 0].std()), float(Aa[:, 1].std())]}

    # ---- the floor, at both linearisation points ----
    pairs = [('theta_true', theta_true)] + ([('theta_dep', theta_dep)] if detuned else [])
    for tag, th in pairs:
        print(f'\nbuilding Q at {tag}...', flush=True)
        Q, S, rk = build_Q(CFG, norm, X_flat, U_flat, sub_ix, r_phys, th, tag)
        proj = Q.T @ D
        floor = float(np.linalg.norm(proj) / nD)
        print(f'  FLOOR at {tag}: ||Q^T Delta|| / ||Delta|| = {floor:.6f}  '
              f'({100*floor:.3f}% of the true residual is in span(Phi))')
        res[f'floor_{tag}'] = floor
        res[f'rank_{tag}'] = int(rk)
        res[f'sigma_rel_last_{tag}'] = float(S[rk-1]/S[0])

    with open(OUT, 'w', encoding='utf-8') as fh:
        json.dump(res, fh, indent=2)
    print(f'\nwrote {OUT}')


if __name__ == '__main__':
    main()
