"""Is the controller subtraction valid when the model is NONLINEAR?

THE OBJECTION
-------------
"You train in closed loop, the plant is LPV and the ANN correction is nonlinear, so you cannot
just subtract the difference in the controller output."

THE CLAIM
---------
    u_d = Cfb(r - y_d) + f_ms          machine loop
    u_m = Cfb(r - y_m) + f_ms          same controller around the model
    ------------------------------------------------------------------- subtract
    u_m = u_d + Cfb(y_d - y_m)                                          RESIDUAL FORM

Define the machine-loop DEFECT at the rate the training loop runs at,

    delta[k] := u_d[k] - ( Cfb(r - y_d)[k] + f_ms[k] )

Then for ANY model, linear or not, e_direct = (r - y_m) = (r - y_d) + (y_d - y_m) and linearity
of Cfb alone give

    u_direct[k] - u_residual[k] = delta[k]                                            (*)

i.e. the gap between the two forms is a MODEL-INDEPENDENT signal fixed by the data and the
controller. The nonlinearity lives in f, which the derivation never touches.

WHAT VERSION 1 OF THIS SCRIPT GOT WRONG
---------------------------------------
It compared 20000-step rollouts and found the two forms agreeing to 4.6e-9 m with the ANN off but
disagreeing at 7e-4 m, comparable to the model error itself, with the ANN on. That does NOT
distinguish the two candidate causes:

  (i)  the algebra is wrong, so the gap is O(model error) from the first step;
  (ii) the algebra is exact but the two arms are different floating-point programs, and a strongly
       nonlinear closed loop amplifies the eps-level difference exponentially over 20000 steps.

A single end-of-rollout number cannot tell those apart. This version separates them with four
measurements, of which T2, T3 and T4 are the discriminating ones.

  T1  ONE STEP, arbitrary states. Both forms evaluated at random model states and random
      controller states. No accumulation at all, so this is the algebraic identity on its own.
      Cause (i) fails here; cause (ii) cannot appear here.
  T2  GROWTH CURVE. |y_direct - y_residual| as a function of step index, next to a CONTROL: the
      residual form re-run from an x0 perturbed by one float32 eps. If the direct-vs-residual gap
      tracks the control curve, the gap IS numerical noise being amplified, and the amplification
      is a property of the model, not of the loop form.
  T3  PRECISION. The same experiment in float32 and in float64. Cause (i) is precision-blind;
      cause (ii) must drop by orders of magnitude.
  T4  TRAINING GEOMETRY. The horizon that actually matters is nf, the training window, not 20000
      steps. Reported over many windows.

TWO CONDITIONS FOR (*), TESTED NOT ASSUMED
------------------------------------------
  C1  both loops apply the SAME operator Cfb. True here: Cfb is built at the record's frozen Y_op,
      read from the record, so it is exogenous. A controller scheduled on the MODEL's own state
      would break this while still being linear, which is the failure mode worth naming.
  C2  consistent controller states, xc_direct = xc_D + xc_residual. The residual arm starts at
      xc_residual = 0, so the direct arm starts from the machine's reconstructed xc_D, obtained by
      filtering (r - y_d) from k = 0. Zeroing both would smuggle the SEPARATE xc = 0 approximation
      into a test that is not about it.

delta != 0 for these records, because they were generated by a 20 kHz controller while the
training loop runs at 4 kHz with Cfb re-discretised (D-141). Every arm below therefore uses
u_data := Cfb(r - y_d) + f_ms, the input CONSISTENT with the training-rate controller, so delta
is zero by construction and the algebra is isolated. The size of delta is reported separately.

Usage
-----
  PYTHONUNBUFFERED=1 python -u cl_direct_vs_residual.py
"""
__project_origin__ = "added"

import dataclasses
import os
import sys
import time

import numpy as np
import torch
from scipy.io import loadmat

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
GANTRY = os.path.join(REPO, 'scripts', 'gantry')
for p in (REPO, GANTRY, HERE, os.path.join(GANTRY, 'drift-demo'),
          os.path.join(GANTRY, 'msd-offset')):
    if p not in sys.path:
        sys.path.insert(0, p)

import demo_common as dm                                                  # noqa: E402
from demo_common import CFG                                               # noqa: E402
from gantry_dynamic.data import traj_dir, _resample_u                     # noqa: E402

import cl_plant as PLANT                                                  # noqa: E402
import cl_validation as CV                                                # noqa: E402
from cl_controller import ControllerBank, rollout, y_op_for               # noqa: E402
from model_augmentation.fit_systems.blocks import Static_ANN_Block        # noqa: E402

RECORD = 'V1_standstill_Yp10'
ANN_GAINS = [0.0, 1e-2, 1e-1]
GROWTH_GAIN = 1e-2               # gain used for the T2 growth curve and T3 precision test
N_LONG = 20000                   # long horizon, the one v1 used
N_ONE_STEP = 64                  # random states for T1
N_WINDOWS = 64                   # training windows for T4
CH = ['X1', 'X2', 'Y']
t0 = time.time()


def rms(a, axis=0):
    return np.sqrt(np.mean(np.asarray(a) ** 2, axis=axis))


def line(label, v, fmt='%.3e'):
    return '    %-42s [' % label + ' '.join(fmt % x for x in v) + ']'


# ---------------------------------------------------------------------------------------------

def set_ann_gain(fs, gain, seed=0):
    """Re-initialise the ANN's LAST layer so its output is nonzero and nonlinear.

    build_pipeline ships a zero-init ANN (exact zero output), so without this the 'augmented'
    model is the LPV baseline. Only the output layer is touched: the hidden tanh layers keep
    their random init, so the map is genuinely nonlinear rather than a rescaled linear one.
    """
    ann = next(m for m in fs.hfn.connected_blocks if isinstance(m, Static_ANN_Block))
    last = [m for m in ann.net.modules() if isinstance(m, torch.nn.Linear)][-1]
    g = torch.Generator().manual_seed(seed)
    with torch.no_grad():
        w = torch.randn(last.weight.shape, generator=g, dtype=last.weight.dtype)
        b = torch.randn(last.bias.shape, generator=g, dtype=last.bias.dtype)
        last.weight.copy_(w * gain / max(1.0, np.sqrt(last.weight.shape[1])))
        last.bias.copy_(b * gain * 0.1)
    return ann


def machine_controller(r_phys, y_phys, ctrl_np):
    """Filter the MACHINE's error (r - y_data) from rest. Returns (u_fb [N], xc trajectory)."""
    Ac, Bc, Cc, Dc = ctrl_np
    N = len(r_phys)
    xc = np.zeros(Ac.shape[0])
    u = np.empty((N, Cc.shape[0]))
    xs = np.empty((N, Ac.shape[0]))
    for k in range(N):
        e = r_phys[k] - y_phys[k]
        xs[k] = xc
        u[k] = Cc @ xc + Dc @ e
        xc = Ac @ xc + Bc @ e
    return u, xs


def direct_rollout(step_fn, out_fn, r_phys, f_phys, x0, xc0, ctrl_np, norm, dtype):
    """Cfb closed around the model from the REFERENCE. Controller error is r - y_model [m]."""
    Ac, Bc, Cc, Dc = ctrl_np
    ystd = np.asarray(norm.ystd).ravel()
    y0 = np.asarray(norm.y0).ravel()
    u_mean = np.asarray(norm.u_mean).ravel()
    std_u = np.asarray(norm.std_u).ravel()
    x = x0
    xc = np.asarray(xc0, float).copy()
    ys = []
    with torch.no_grad():
        for k in range(len(r_phys)):
            y_n = out_fn(x)
            ys.append(y_n)
            e = r_phys[k] - (y_n[0].numpy().astype(float) * ystd + y0)
            u_phys = Cc @ xc + Dc @ e + f_phys[k]
            u_n = (u_phys - u_mean) / std_u
            x = step_fn(x, torch.as_tensor(u_n[None, :], dtype=dtype))
            xc = Ac @ xc + Bc @ e
    return torch.cat(ys, dim=0).numpy()


# ---------------------------------------------------------------------------------------------

def build(use_f64):
    cfg = dataclasses.replace(CFG, seed=0, use_f64=use_f64)
    fs, norm, K0, na, nb, na_r, nb_r = dm.build_pipeline(cfg=cfg, verbose=False)
    nx = cfg.nx_phys + cfg.nx_ann
    C_out, b_out = PLANT.identify_output_map(fs.hfn, nx, cfg.nu, dtype=cfg.dtype_pt)
    step_fn, out_fn = PLANT.make_fns(fs, C_out, b_out)
    bank = ControllerBank([RECORD], cfg.ts_new, dtype=cfg.dtype_pt,
                          ystd=norm.ystd, std_u=norm.std_u)
    return cfg, fs, norm, K0, na, nb, na_r, nb_r, step_fn, out_fn, bank, nx


def signals(cfg, norm, K0, n_need):
    """Record signals at the TRAINING rate, plus the consistent input and the machine xc."""
    d = loadmat(os.path.join(traj_dir(cfg), RECORD + '.mat'), squeeze_me=True)
    D = cfg.d
    u_raw = _resample_u(np.asarray(d['u_total'], float), cfg)
    f_raw = _resample_u(np.asarray(d['f_sim'], float), cfg)
    N = min(len(u_raw), len(f_raw), K0 + n_need)
    return dict(N=N, u=u_raw[:N], f=f_raw[:N],
                r=np.asarray(d['r_sim'], float)[::D][:N],
                y=np.asarray(d['y'], float)[::D][:N])


print('=' * 104)
print('DIRECT vs RESIDUAL closed-loop form, with a NONLINEAR augmented model')
print('=' * 104)
print('building float32 pipeline ...', flush=True)
cfg, fs, norm, K0, na, nb, na_r, nb_r, step_fn, out_fn, bank, nx = build(False)
print('training rate %d Hz, decimation %d, dtype %s, nf = %d'
      % (cfg.fs_new_hz, cfg.d, cfg.dtype_np.__name__, cfg.nf))
ft = PLANT.check_no_feedthrough(fs.hfn, nx, cfg.nu, dtype=cfg.dtype_pt)
print('D_d = 0 check: %.3e   %s' % (ft, 'OK' if ft == 0.0 else 'NONZERO'))

sig = signals(cfg, norm, K0, N_LONG)
N = sig['N']
ystd = np.asarray(norm.ystd).ravel()
row = bank.rec_to_ctrl[0].item()
ctrl_np = tuple(bank.__getattr__(k)[row].numpy().astype(float) for k in 'ABCD')
ctrl_t = bank.gather(torch.tensor([0], dtype=torch.long))

u_fb_D, xc_D = machine_controller(sig['r'], sig['y'], ctrl_np)
u_cons = u_fb_D + sig['f']
delta = sig['u'] - u_cons
print('\n%s  Y_op %+.2f m' % (RECORD, y_op_for(RECORD)))
print(line('rms u_fb from (r - y_d) [N]', rms(u_fb_D)))
print(line('rms delta = u_total - (u_fb + f_ms) [N]', rms(delta)))
print(line('delta / u_fb  (the 20k->4k gap)', rms(delta) / rms(u_fb_D), '%9.5f'))
print('    every arm below uses u_data := u_fb + f_ms, so delta = 0 by construction')

yn = ((sig['y'] - np.asarray(norm.y0).ravel()) / ystd).astype(cfg.dtype_np)
un = PLANT.normalise_u(u_cons, norm, cfg.dtype_np)

# =============================================================================================
print('\n' + '=' * 104)
print('T1  ONE STEP, arbitrary model states and arbitrary controller states (no accumulation)')
print('=' * 104)
Ac, Bc, Cc, Dc = ctrl_np
u_mean = np.asarray(norm.u_mean).ravel()
std_u = np.asarray(norm.std_u).ravel()
y0v = np.asarray(norm.y0).ravel()

for gain in ANN_GAINS:
    set_ann_gain(fs, gain)
    g = torch.Generator().manual_seed(7)
    xs = torch.randn(N_ONE_STEP, nx, generator=g, dtype=cfg.dtype_pt)
    ks = np.linspace(K0, N - 2, N_ONE_STEP).astype(int)
    xc_res = np.random.RandomState(3).randn(N_ONE_STEP, Ac.shape[0]) * 1e3
    worst = 0.0
    with torch.no_grad():
        for i, k in enumerate(ks):
            y_n = out_fn(xs[i:i + 1])[0].numpy().astype(float)
            y_phys = y_n * ystd + y0v
            # residual arm
            e_res = (yn[k] - y_n) * ystd
            u_res = u_cons[k] + (Cc @ xc_res[i] + Dc @ e_res)
            # direct arm, with the consistent controller state xc_D + xc_res
            e_dir = sig['r'][k] - y_phys
            u_dir = Cc @ (xc_D[k] + xc_res[i]) + Dc @ e_dir + sig['f'][k]
            worst = max(worst, float(np.max(np.abs(u_dir - u_res))))
    print('  ANN gain %-6.3g   worst |u_direct - u_residual| over %d states : %.3e N'
          % (gain, N_ONE_STEP, worst))
print('  (rms u_fb is %.2e N, so this is the identity at machine precision regardless of the ANN)'
      % float(np.max(rms(u_fb_D))))

# =============================================================================================
print('\n' + '=' * 104)
print('T2  GROWTH CURVE at ANN gain %.3g, against a one-eps initial-state perturbation'
      % GROWTH_GAIN)
print('=' * 104)
set_ann_gain(fs, GROWTH_GAIN)
x0 = CV.encoder_x0(fs.encoder, un, yn, K0, na, nb, na_r, nb_r, cfg.dtype_pt)
u_t = torch.as_tensor(np.ascontiguousarray(un[None, K0:N]), dtype=cfg.dtype_pt)
y_t = torch.as_tensor(np.ascontiguousarray(yn[None, K0:N]), dtype=cfg.dtype_pt)
with torch.no_grad():
    y_res, _, _ = rollout(step_fn, out_fn, u_t, y_t, x0, bank, ctrl_t)
    x0p = x0 * (1.0 + torch.finfo(cfg.dtype_pt).eps)          # CONTROL: one eps on the state
    y_ctl, _, _ = rollout(step_fn, out_fn, u_t, y_t, x0p, bank, ctrl_t)
y_res = y_res[0].numpy()
y_ctl = y_ctl[0].numpy()
y_dir = direct_rollout(step_fn, out_fn, sig['r'][K0:N], sig['f'][K0:N], x0, xc_D[K0],
                       ctrl_np, norm, cfg.dtype_pt)

gap = np.abs(y_dir - y_res).max(axis=1) * float(np.max(ystd))
ctl = np.abs(y_ctl - y_res).max(axis=1) * float(np.max(ystd))
err = np.abs(y_res - yn[K0:N]).max(axis=1) * float(np.max(ystd))
print('  %-10s %-14s %-14s %-14s' % ('step', 'direct-resid', 'eps-perturbed', 'model error'))
for k in (1, 3, 10, 30, 100, 300, 1000, 3000, 10000, len(gap) - 1):
    if k < len(gap):
        print('  %-10d %-14.3e %-14.3e %-14.3e' % (k, gap[k], ctl[k], err[k]))
print('  If the two left columns track each other, the direct-vs-residual gap IS float noise')
print('  amplified by the model, not an algebra error (which would be O(model error) at step 1).')

# =============================================================================================
print('\n' + '=' * 104)
print('T3  PRECISION: the same comparison in float32 and float64')
print('=' * 104)
print('  building float64 pipeline ...', flush=True)
c64, fs64, n64, K64, na4, nb4, nar4, nbr4, step64, out64, bank64, nx64 = build(True)
set_ann_gain(fs64, GROWTH_GAIN)
sig64 = signals(c64, n64, K64, N_LONG)
ystd64 = np.asarray(n64.ystd).ravel()
row64 = bank64.rec_to_ctrl[0].item()
ctrl64 = tuple(bank64.__getattr__(k)[row64].numpy().astype(float) for k in 'ABCD')
ctrl_t64 = bank64.gather(torch.tensor([0], dtype=torch.long))
ufb64, xcD64 = machine_controller(sig64['r'], sig64['y'], ctrl64)
ucons64 = ufb64 + sig64['f']
yn64 = ((sig64['y'] - np.asarray(n64.y0).ravel()) / ystd64).astype(c64.dtype_np)
un64 = PLANT.normalise_u(ucons64, n64, c64.dtype_np)
N64 = sig64['N']

HORIZONS = [100, 1000, 10000]
print('  %-10s %-18s %-18s %-14s' % ('horizon', 'float32 gap [m]', 'float64 gap [m]', 'ratio'))
for H in HORIZONS:
    H32 = min(H, len(gap) - 1)
    g32 = float(np.max(gap[:H32 + 1]))
    x064 = CV.encoder_x0(fs64.encoder, un64, yn64, K64, na4, nb4, nar4, nbr4, c64.dtype_pt)
    end = min(K64 + H + 1, N64)
    ut = torch.as_tensor(np.ascontiguousarray(un64[None, K64:end]), dtype=c64.dtype_pt)
    yt = torch.as_tensor(np.ascontiguousarray(yn64[None, K64:end]), dtype=c64.dtype_pt)
    with torch.no_grad():
        yr64, _, _ = rollout(step64, out64, ut, yt, x064, bank64, ctrl_t64)
    yd64 = direct_rollout(step64, out64, sig64['r'][K64:end], sig64['f'][K64:end], x064,
                          xcD64[K64], ctrl64, n64, c64.dtype_pt)
    g64 = float(np.max(np.abs(yd64 - yr64[0].numpy()) * ystd64))
    print('  %-10d %-18.3e %-18.3e %-14.3g' % (H, g32, g64, g32 / max(g64, 1e-300)))
print('  An ALGEBRA error is precision-blind (ratio ~ 1). Float noise scales with eps (~1e8-1e9).')

# =============================================================================================
print('\n' + '=' * 104)
print('T4  TRAINING GEOMETRY: horizon nf = %d, the window the loss actually uses' % cfg.nf)
print('=' * 104)
starts = np.linspace(K0, N - cfg.nf - 2, N_WINDOWS).astype(int)
print('  %-8s %-16s %-16s %-10s' % ('ANN', 'max gap [m]', 'model err [m]', 'gap/err'))
for gain in ANN_GAINS:
    set_ann_gain(fs, gain)
    gaps, errs = [], []
    for s in starts:
        x0w = CV.encoder_x0(fs.encoder, un, yn, int(s), na, nb, na_r, nb_r, cfg.dtype_pt)
        uw = torch.as_tensor(np.ascontiguousarray(un[None, s:s + cfg.nf]), dtype=cfg.dtype_pt)
        yw = torch.as_tensor(np.ascontiguousarray(yn[None, s:s + cfg.nf]), dtype=cfg.dtype_pt)
        with torch.no_grad():
            yr, _, _ = rollout(step_fn, out_fn, uw, yw, x0w, bank, ctrl_t)
        yr = yr[0].numpy()
        yd = direct_rollout(step_fn, out_fn, sig['r'][s:s + cfg.nf], sig['f'][s:s + cfg.nf],
                            x0w, xc_D[s], ctrl_np, norm, cfg.dtype_pt)
        gaps.append(np.max(np.abs(yd - yr) * ystd))
        errs.append(np.sqrt(np.mean(((yr - yn[s:s + cfg.nf]) * ystd) ** 2)))
    gmax, emax = float(np.max(gaps)), float(np.mean(errs))
    print('  %-8.3g %-16.3e %-16.3e %-10.3e' % (gain, gmax, emax, gmax / max(emax, 1e-30)))

set_ann_gain(fs, 0.0)
print('\n[%.0fs]' % (time.time() - t0))
