function export_baseline_closedloop()
% EXPORT_BASELINE_CLOSEDLOOP  MATLAB reference for the BASELINE model in closed loop.
%
%   Curve 1 of the three-curve comparison. The baseline model is the 6-state rigid FP
%   model (gtd_build_plant's `sys`: full payload mass mh, NO absorber, NO ANN). The record
%   was generated by the 8-state truth WITH the hidden MSD, so the difference between this
%   replay and the record is exactly the absorber discrepancy.
%
%   The loop is closed in the RESIDUAL FORM, which is what loss_variants.py:136-138 uses
%   and therefore what variant B trains:
%
%       u_model(k) = u_data(k) + Cfb * ( y_data(k) - y_model(k) )
%
%   exact because Cfb is linear. The controller state for the residual channel starts at
%   zero, which is correct rather than approximate: the record's own controller action is
%   already carried by u_data at every sample.
%
%   WHY THIS FILE EXISTS. The controller alone is gated against MATLAB to 1.9e-16
%   (RESULT.md, L4ss) and the closed-loop wiring to 1.1e-12 m (p1_equivalence.py), but the
%   latter used the TRUTH model. The BASELINE model in closed loop has never been compared
%   against an independent implementation. This supplies that reference.
%
%   Everything runs at cfg.ts (20 kHz) in double, so the Python side can separate:
%     curve 1 vs 2   implementation      (this file vs Python, same rate, same Cfb)
%     curve 2 vs 3   rate and precision  (20 kHz double vs 4 kHz float32, both Python)
%
%   No Simulink, no plant regeneration, no record modified. Reads the records, writes one
%   new file next to this script. Saved -v7 so scipy.io.loadmat reads it without h5py.

    here = fileparts(mfilename('fullpath'));
    root = fileparts(fileparts(fileparts(here)));
    addpath(fullfile(root, 'Matlab-scripts', 'Augmentation', 'data'));

    traj  = fullfile(root, 'data', 'gantry', 'matlab', 'trajectory', 'augmentation');
    names = {'V1_standstill_Yp10', 'T10_aprbs_60'};
    Y_ops = [0.10, 0.00];                          % gtd_build_records.m

    cfg = gtd_config('augmentation', true, 0.10);

    for i = 1:numel(names)
        rec = load(fullfile(traj, [names{i} '.mat']), 'y', 'u_total');
        y_data  = double(rec.y);
        u_data  = double(rec.u_total);
        N       = size(y_data, 1);

        plant = gtd_build_plant(Y_ops(i), cfg);
        Cfb   = plant.Cfb;                 % 9-state, stage frame, m -> N
        Gd    = plant.G;                   % baseline, discrete ZOH, logical coords

        % Discrete baseline in logical coordinates, driven by LOGICAL force.
        % gtd_build_plant already folds P in:  sys = P' * getss(...) * P, so Gd maps
        % STAGE force -> STAGE position directly. No further transform is needed.
        Ad = Gd.A;  Bd = Gd.B;  Cd = Gd.C;  Dd = Gd.D;
        nx = size(Ad, 1);

        % Controller state space (residual channel).
        Ac = Cfb.A;  Bc = Cfb.B;  Cc = Cfb.C;  Dc = Cfb.D;
        nc = size(Ac, 1);

        % Initial plant state: the generator's integrator IC is q = [0, 0, Y_op].
        % Gd's states are [q; qdot] in the same order as getss.
        x  = zeros(nx, 1);
        x(3) = Y_ops(i);
        xc = zeros(nc, 1);

        y_ol = zeros(N, 3);
        y_cl = zeros(N, 3);

        % --- open loop: recorded force, no correction --------------------------------
        for k = 1:N
            y_ol(k, :) = (Cd * x + Dd * u_data(k, :).').';
            x = Ad * x + Bd * u_data(k, :).';
        end

        % --- closed loop: residual form ----------------------------------------------
        x = zeros(nx, 1);  x(3) = Y_ops(i);
        for k = 1:N
            y        = Cd * x;                        % Dd = 0 for this plant
            y_cl(k, :) = y.';
            dy       = y_data(k, :).' - y;            % [m]
            u_fb     = Cc * xc + Dc * dy;             % [N]
            u        = u_data(k, :).' + u_fb;
            x        = Ad * x + Bd * u;
            xc       = Ac * xc + Bc * dy;
        end

        S = struct();
        S.name   = names{i};
        S.Y_op   = Y_ops(i);
        S.ts     = cfg.ts;
        S.y_ol   = y_ol;
        S.y_cl   = y_cl;
        S.y_data = y_data;

        out = fullfile(here, sprintf('baseline_closedloop_%s.mat', names{i}));
        save(out, '-struct', 'S', '-v7');

        e_ol = y_ol - y_data;   e_cl = y_cl - y_data;
        fprintf('%-22s Y_op %.2f  N %6d  ts %.3e\n', names{i}, Y_ops(i), N, cfg.ts);
        fprintf('   open   loop err rms [%.4e %.4e %.4e] m\n', rms(e_ol));
        fprintf('   CLOSED loop err rms [%.4e %.4e %.4e] m\n', rms(e_cl));
        fprintf('   wrote %s\n', out);
    end
end

function r = rms(v)
    r = sqrt(mean(v.^2, 1));
end
