"""Shared constants, palette and axis helpers for the 2026-09-21 settling figures.

No plotting and no simulation live here: this is what `collect.py` and `fig_settling.py` must
AGREE on, and nothing else.

WHAT THESE FIGURES ARE FOR. Quinten, meeting 2026-09-18: "Plaatje inzoomt op settling", and
crucially "Voor het model vooral het gedrag van hoe die settled, system afhankelijk niet het
model". The settling itself is a property of the plant and its controller, not of the model, so
these figures do NOT report a settling time and do NOT draw a tolerance band. They show the
BEHAVIOUR of each model during the settling window, against the data, and let the arms be
compared to each other. That is also why no epsilon is defined anywhere in this folder: the data
is noiseless (`SNR = None`), so there is no noise floor to derive one from, and a hand-picked
band would decide the figure by itself.

THE RECORD is `S1_settle_Ylow_noexc`, generated by
`Matlab-scripts/Augmentation-settling/data/generate_trajectory_data_settling.m` (D-205). It is
the validation jerk-limited profile with the injected multisine OFF and a 0.4 s dwell between
moves. The multisine had to be removed at GENERATION time, not afterwards: `gtd_run_simulation.m`
forms `u_fb = lsim(Cfb, r_sim - q_with)` against the output with the multisine acting, so the
controller responded to it and `u_fb` carries a multisine-induced component of its own.

MEASURED, and the reason to read the zoom panels with care: this record's absorber deflection is
`rms 5.95e-06 m`, against `4.50e-05 m` on V2 (multisine on) and `1.63e-05 m` on E4. With the
excitation off, the 212.13 Hz coupled mode is driven only by the jerk transients. If the arms
draw on top of each other in the zoom, that is a statement about excitation, not a broken figure.

NAMING, carried over from the 2026-09-07 set because the same two traps apply.

`y` is NOT a measurement. `SNR: null`, so it is the noiseless output of the MATLAB simulation of
the extended plant, the FP model plus the hidden mass-spring-damper absorber, decimated to 4 kHz.
It is called "system" on every figure, never "measured".

`y_hat` is NOT a free run. The loop is

    y_hat[k]      = C x[k]
    u_fb[k], xc   = Cfb(xc, y_data[k] - y_hat[k])
    x[k+1]        = f(x[k], u_data[k] + u_fb[k])

so the recorded output enters through the controller at EVERY timestep. What is free is the model
STATE: x is propagated by the model and never teacher-forced, and x_0 comes from the encoder
window alone. Every arm, the baseline included, runs this identical loop; the ONLY difference
between arms is the ANN. Panels say "closed loop" so the ambiguity is never silent.

Layout:
    fig_common.py    this file: paths, arms, palette, axis helpers
    build.py         checkpoint -> closed-loop system (the only file that touches torch weights)
    collect.py       the only file that simulates; writes settling_data.npz
    fig_settling.py  redraws the five figures from the cache in a second
"""
__project_origin__ = "added"

import pathlib
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
MEETING = HERE.parent
ROOT = HERE.parents[4]

# The OBC arms live in the PREVIOUS meeting's folder, because that is where the server results
# were copied back to. Pointing at them rather than re-copying keeps one source of truth.
CKPT_DIR = MEETING.parent / 'meeting-18-09-2026' / 'server' / 'useable'
FIGDIR = MEETING / 'figures'

# ── The record ──────────────────────────────────────────────────────────────────────────────
TRAIN_MODE = 'augmentation_ma50_b140-230_a6_z03'   # what the checkpoints were trained on
SETTLE_MODE = 'augmentation_ma50_z03_settle_noexc'  # the new record's folder (D-205)
RECORD = 'S1_settle_Ylow_noexc'
RECORD_MAT = RECORD + '.mat'

# S1 was generated at Y_op = -0.22, the same operating point as V2_aprbs_Ylow. The controller
# bank is keyed by Y_op, so S1's controller IS V2's row, and borrowing it is exact rather than
# approximate. This is also why nothing in `gantry_dynamic/controller.py` needs a new entry:
# the bank is never rebuilt, only indexed. `collect.py` asserts the row it borrowed.
CTRL_DONOR = 'V2_aprbs_Ylow'
VERIFY_RECORD = 'V2_aprbs_Ylow.mat'   # re-simulated so the loaded weights can be checked

FS = 4000.0                            # cfg.fs_new [Hz]
CHANNELS = ['X1', 'X2', 'Y']
INK, MUTED = '#222222', '#777777'
C_DATA = '#7A3E9D'                     # the simulated y, wherever it is drawn against a model

# ── The arms ────────────────────────────────────────────────────────────────────────────────
# All four run the identical closed loop; only the ANN differs.
#
#   baseline  the same architecture at its INITIALISATION: linear-map encoder, ANN output
#             exactly zero, so the augmented states are inert and nothing but the FP model is
#             left in the loop. With JOINT_ESTIMATION = True these runs start from
#             COMBO_INIT_DETUNE = [1.1, 1.1, 0.9, ...], i.e. physical parameters detuned by
#             +/-10%, so this arm is honestly "what you had before training", NOT the FP model
#             at its true parameters. It is drawn thick and underneath.
#   84032     no projection
#   84033     OBC, tangent space (10 columns)
#   84037     OBC, affine space (11 columns)
#
# 84034 is NOT here. It is a repeat of the affine arm with a byte-identical config apart from
# run_id, it stopped at iteration 14300 against 84037's 18200, and `meeting-18-09-2026/figures/
# OBC/obc_data.json` already labels it `affine_dup`.
#
# Colours are assigned by ENTITY and never cycled; every arm also carries its own dash pattern,
# so identity survives a greyscale print and a CVD reader.
ARMS = {
    'baseline': dict(run='84032', weights=False, label='baseline (FP, ANN zero)',
                     c='#D55E00', ls='-', lw=1.6, z=1),
    'noproj':   dict(run='84032', weights=True,  label='no projection',
                     c='#0072B2', ls='-', lw=1.1, z=4),
    'tangent':  dict(run='84033', weights=True,  label='OBC, tangent (10 col)',
                     c='#009E73', ls='--', lw=1.1, z=3),
    'affine':   dict(run='84037', weights=True,  label='OBC, affine (11 col)',
                     c='#CC79A7', ls=':', lw=1.3, z=2),
}
ARM_ORDER = ['baseline', 'noproj', 'tangent', 'affine']


def ckpt_path(run):
    """deepSI's whole-system dump. 84034/84037 have ONLY this, no .pt/.npz pair."""
    return CKPT_DIR / ('SSE_Interconnect_Composed_%s_best.pth' % run)


def config_path(run):
    return CKPT_DIR / run / 'config.json'


def cache_path():
    return HERE / 'settling_data.npz'


def add_repo_to_path():
    """Put the repo root and `scripts/gantry` on sys.path. Only the simulating code needs this."""
    for p in (ROOT, ROOT / 'scripts' / 'gantry'):
        if str(p) not in sys.path:
            sys.path.insert(0, str(p))


# =================================================================================================
# Finding the settling windows
# =================================================================================================

def move_edges(r, tol=0.0):
    """(starts, stops) sample indices of every setpoint MOVE in a decimated reference `r`.

    A sample is "moving" if the reference changes between it and the next. Derived from `r_sim`
    rather than from `y`, because `y` never stops moving: the absorber rings through the dwell,
    which is the entire point of the figure.
    """
    r = np.asarray(r, dtype=np.float64)
    moving = (np.abs(np.diff(r, axis=0)) > tol).any(axis=1)
    edges = np.diff(np.concatenate([[0], moving.astype(int), [0]]))
    return np.flatnonzero(edges == 1), np.flatnonzero(edges == -1)


def settling_windows(r, min_dwell_s=0.30):
    """Every (move_end, dwell_end) pair with at least `min_dwell_s` of dwell after it.

    These are the settling events. A move whose travel is zero is dropped: the APRBS draw can
    land on the current setpoint, and a no-op move is not a settling event.
    """
    starts, stops = move_edges(r)
    travel = np.array([np.abs(r[min(e, len(r) - 1)] - r[s]).max() for s, e in zip(starts, stops)])
    n_min = int(round(min_dwell_s * FS))
    out = []
    for j, (s, e) in enumerate(zip(starts, stops)):
        nxt = starts[j + 1] if j + 1 < len(starts) else len(r)
        if travel[j] > 0 and (nxt - e) >= n_min:
            out.append((int(e), int(nxt), float(travel[j])))
    return out


def pick_window(r, dur_s=0.40):
    """The settling window to zoom on: the dwell after the LARGEST move.

    Picked from the data, not by hand, so the same rule applies to every arm and to any record
    this code is later pointed at. The largest move is the one that rings the 212.13 Hz mode
    hardest, which is where the arms have the best chance of separating.
    """
    w = settling_windows(r)
    if not w:
        raise SystemExit('no settling window with enough dwell in this record')
    e, nxt, _ = max(w, key=lambda x: x[2])
    n = int(round(dur_s * FS))
    return int(e), int(min(e + n, nxt, len(r)))


# =================================================================================================
# Plot helpers
# =================================================================================================

def style():
    """Matplotlib rcParams, identical across the figures so they read as one set."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    plt.rcParams.update({
        'font.size': 8, 'axes.labelsize': 8, 'axes.titlesize': 8.5,
        'legend.fontsize': 7.5, 'xtick.labelsize': 7.5, 'ytick.labelsize': 7.5,
        'axes.edgecolor': MUTED, 'axes.labelcolor': INK, 'text.color': INK,
        'xtick.color': MUTED, 'ytick.color': MUTED,
        'axes.grid': True, 'grid.color': '#e6e6e6', 'grid.linewidth': 0.6,
        'axes.spines.top': False, 'axes.spines.right': False,
        'figure.facecolor': 'white', 'axes.facecolor': 'white',
        'savefig.dpi': 200, 'savefig.bbox': 'tight',
    })
    return plt


def sci_axis(ax):
    """Scientific notation with an explicit 1e-N offset. The display contract's first line."""
    ax.ticklabel_format(axis='y', style='sci', scilimits=(0, 0), useMathText=True)
    ax.yaxis.get_offset_text().set_fontsize(7)
    ax.yaxis.get_offset_text().set_color(MUTED)


def two_col_axes(plt, nrows, figsize):
    """A (nrows, 2) grid: the FULL record on the left, the settling zoom on the right.

    The columns do NOT share a y-axis. The setpoint travel is 1e-01 m and what happens during a
    dwell is 1e-05 m, so a shared scale renders the zoom as a flat line and shows nothing at all.
    Each column carries its own tick labels, so the second scale is stated rather than silent.
    """
    fig, axes = plt.subplots(nrows, 2, figsize=figsize, squeeze=False,
                             gridspec_kw={'width_ratios': [2.1, 1]})
    for r in range(1, nrows):
        for c in (0, 1):
            axes[r][c].sharex(axes[0][c])
    return fig, axes


def finish_columns(axes, t_full, twin, zoom_note=''):
    """x-limits and x-labels for a `two_col_axes` grid. Call once, after all the plotting."""
    axes[0][0].set_xlim(float(t_full[0]), float(t_full[-1]))
    axes[0][1].set_xlim(*twin)
    for r in range(len(axes) - 1):
        for c in (0, 1):
            axes[r][c].tick_params(labelbottom=False)
    axes[-1][0].set_xlabel('time [s]')
    axes[-1][1].set_xlabel('time [s]')
    title = '%.2f to %.2f s' % twin
    if zoom_note:
        title += '   %s' % zoom_note
    axes[0][1].set_title(title, fontsize=8, color=MUTED, pad=4)


def load_cache():
    p = cache_path()
    if not p.exists():
        raise SystemExit(
            'no cache at %s. Run `python collect.py` first: it is the only script here that '
            'simulates, and every figure then redraws from it in a second.' % p)
    return dict(np.load(p, allow_pickle=True))
