"""
data_utils.py
-------------
Data loading and RMSE_baseline computation for the gantry parameter recovery
experiment (Step 3b, D-033, D-034).

Provides
--------
load_gantry_data(mat_path, train_fraction)
    Load lpv_sim_varying_y.mat and return deepSI System_data for train and val.

compute_rmse_baseline(mat_path)
    Run the detuned ParameterizedLFRBlock in open loop on the MATLAB trajectory.
    Returns RMSE in metres -- used as RMSE_baseline when constructing
    ParameterizedLFRBlock for training (D-034).

Data source: Matlab-output/lpv_sim_varying_y.mat
    Generated by Matlab-scripts/export_lpv_sim.m using true physical parameters.
    Variables: u_q1 (N,3) stage forces [N], q1 (N,3) stage positions [m],
    fs=20000 Hz, N=35001 samples, duration 1.75 s.
    Y sweeps 0.3 -> -0.3 m (full operational range), exciting M(Y) variation.

x0 derivation:
    q1[0] = [0, 0, 0.3] in stage coords.
    Stage positions = P.T @ logical positions  (physics.py convention).
    At q1[0]=[0,0,0.3]: X1_stage=0, X2_stage=0, Y=0.3
    Solving P.T @ q_logical = [0,0,0.3] gives q_logical = [0, 0, 0.3].
    Initial velocities are zero (system starts at rest).
    So x0_logical = [0, 0, 0.3, 0, 0, 0].
"""

import os
import numpy as np
import torch
from scipy.io import loadmat

from lpv_lfr_baseline.blocks.lfr_param_block import (
    ParameterizedLFRBlock, _build_matrices, _Lb, _d,
)
from lpv_lfr_baseline.core.lfr_matrices import build_G_matrix
from lpv_lfr_baseline.core.physics import P, ts, build_poly_constants
from lpv_lfr_baseline.core.lfr_simulate import simulate

# Default path relative to repo root
_DEFAULT_MAT = os.path.join(
    os.path.dirname(__file__), '..', 'Matlab-output', 'lpv_sim_varying_y.mat'
)

# Initial logical state: positions [0, 0, 0.3], velocities [0, 0, 0]
_X0_LOGICAL = torch.tensor([[0.0, 0.0, 0.3, 0.0, 0.0, 0.0]], dtype=torch.float64)


def load_gantry_data(
    mat_path: str = _DEFAULT_MAT,
    train_fraction: float = 0.8,
) -> tuple:
    """
    Load lpv_sim_varying_y.mat and split into deepSI System_data.

    Parameters
    ----------
    mat_path       : path to the .mat file
    train_fraction : fraction of samples used for training (default 0.8)

    Returns
    -------
    train_data, val_data : deepSI.System_data
        u shape (N, 3) -- stage forces [N]
        y shape (N, 3) -- stage positions [m]
    """
    try:
        import deepSI
    except ImportError as exc:
        raise ImportError(
            "load_gantry_data requires the optional 'deepSI' dependency."
        ) from exc

    mat = loadmat(mat_path)

    u = mat['u_q1'].astype(np.float32)   # (N, 3) stage forces
    y = mat['q1'].astype(np.float32)     # (N, 3) stage positions

    N = u.shape[0]
    n_train = int(N * train_fraction)

    train_data = deepSI.System_data(u=u[:n_train],  y=y[:n_train])
    val_data   = deepSI.System_data(u=u[n_train:],  y=y[n_train:])

    return train_data, val_data


def compute_rmse_baseline(mat_path: str = _DEFAULT_MAT) -> float:
    """
    Run the detuned ParameterizedLFRBlock in open loop on the MATLAB trajectory.

    Steps
    -----
    1. Load u_q1 (stage forces) and q1 (ground-truth stage positions).
    2. Build detuned matrices from ParameterizedLFRBlock initial params.
    3. Run simulate() with those matrices and x0_logical=[0,0,0.3,0,0,0].
    4. Compute RMS of (y_pred_stage - q1) over all samples and channels.

    Returns
    -------
    rmse : float  -- overall RMSE in metres (D-034)

    Also prints per-channel RMSE for diagnostic purposes.
    """
    mat = loadmat(mat_path)

    u_q1 = torch.tensor(mat['u_q1'], dtype=torch.float64)   # (N, 3)
    q1   = torch.tensor(mat['q1'],   dtype=torch.float64)   # (N, 3)
    N    = u_q1.shape[0]

    # Build detuned matrices and G/poly constants (no gradient needed)
    block = ParameterizedLFRBlock(RMSE_baseline=1.0)
    with torch.no_grad():
        kb1, kb2, cg1, cg2, cy, cb1, cb2, mh, m1, m2, mb, Jb, Jh = block._recover_params()
    M0_d, M1_d, M2_d, K_d, C_d = _build_matrices(
        torch.stack([kb1+kb2, cg1, cg2, cy, cb1+cb2, mh, m1, m2, mb, Jb+Jh]),
        _Lb, _d,
    )
    G_d = build_G_matrix(M0_d, M1_d, M2_d, K_d, C_d)
    alpha_d, beta_d, gamma_d, N0_d, N1_d, N2_d = build_poly_constants(
        m1, m2, mb, mh, Jb, Jh, _Lb, _d
    )

    # simulate() expects (batch, N, 3) inputs
    u_seq = u_q1.unsqueeze(0)   # (1, N, 3)

    print(f"  Running open-loop simulation ({N} steps) with detuned parameters...")
    with torch.no_grad():
        result = simulate(
            _X0_LOGICAL, u_seq,
            G_d, K_d, C_d, mh, alpha_d, beta_d, gamma_d, N0_d, N1_d, N2_d,
            P, ts, bptt_mode='full',
        )

    # result.Y: (1, N, 3) stage positions — squeeze batch dim
    y_pred = result.Y[0]   # (N, 3)

    # Per-channel and overall RMSE
    err        = y_pred - q1                              # (N, 3)
    rmse_ch    = err.pow(2).mean(dim=0).sqrt()            # (3,)
    rmse_total = err.pow(2).mean().sqrt().item()          # scalar

    ch_names = ['X1', 'X2', 'Y']
    print(f"  Per-channel RMSE [m]:")
    for i, name in enumerate(ch_names):
        print(f"    {name}: {rmse_ch[i].item():.6e} m  ({rmse_ch[i].item()*1e3:.4f} mm)")
    print(f"  Overall RMSE: {rmse_total:.6e} m  ({rmse_total*1e3:.4f} mm)")

    return rmse_total


# ----------------------------------------------------------------------
# Verification
# (run as: conda run -n GraduationProject python -m lpv_lfr_baseline.data_utils)
# ----------------------------------------------------------------------
if __name__ == '__main__':
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

    mat_path = _DEFAULT_MAT

    # ------------------------------------------------------------------
    # Check 1 -- Mat file loads correctly, shapes and sampling rate
    # ------------------------------------------------------------------
    print("=" * 60)
    print("Check 1: Mat file loads and has expected structure")
    print("=" * 60)

    mat = loadmat(mat_path)
    u_q1 = mat['u_q1']
    q1   = mat['q1']
    fs   = int(mat['fs'][0, 0])
    t    = mat['t_sim'].squeeze()

    N_ok  = u_q1.shape[0] == 35001
    fs_ok = fs == 20000
    dt_ok = abs((t[1] - t[0]) - 5e-5) < 1e-12
    u_ch  = u_q1.shape[1] == 3
    y_ch  = q1.shape[1] == 3
    y0_ok = np.allclose(q1[0], [0.0, 0.0, 0.3], atol=1e-10)

    print(f"  N = {u_q1.shape[0]}  (expect 35001)  : {N_ok}")
    print(f"  fs = {fs} Hz (expect 20000)         : {fs_ok}")
    print(f"  dt = {t[1]-t[0]:.2e} s (expect 5e-5)  : {dt_ok}")
    print(f"  u channels = {u_q1.shape[1]} (expect 3)        : {u_ch}")
    print(f"  y channels = {q1.shape[1]} (expect 3)        : {y_ch}")
    print(f"  q1[0] = {q1[0]}  (expect [0, 0, 0.3]) : {y0_ok}")
    print(f"  Y range: {mat['Y_trajectory'].min():.3f} to {mat['Y_trajectory'].max():.3f} m")

    status_1 = all([N_ok, fs_ok, dt_ok, u_ch, y_ch, y0_ok])
    print(f"\nCheck 1: {'PASS' if status_1 else 'FAIL'}")

    # ------------------------------------------------------------------
    # Check 2 -- load_gantry_data returns correct deepSI System_data
    # ------------------------------------------------------------------
    print()
    print("=" * 60)
    print("Check 2: load_gantry_data() shapes and types")
    print("=" * 60)

    train_data, val_data = load_gantry_data(mat_path, train_fraction=0.8)

    n_train_expect = int(35001 * 0.8)
    n_val_expect   = 35001 - n_train_expect

    train_u_ok = train_data.u.shape == (n_train_expect, 3)
    train_y_ok = train_data.y.shape == (n_train_expect, 3)
    val_u_ok   = val_data.u.shape   == (n_val_expect,   3)
    val_y_ok   = val_data.y.shape   == (n_val_expect,   3)
    no_overlap = True   # sequential split -- no overlap by construction

    print(f"  train u: {train_data.u.shape}  (expect ({n_train_expect}, 3)) : {train_u_ok}")
    print(f"  train y: {train_data.y.shape}  (expect ({n_train_expect}, 3)) : {train_y_ok}")
    print(f"  val   u: {val_data.u.shape}   (expect ({n_val_expect}, 3))  : {val_u_ok}")
    print(f"  val   y: {val_data.y.shape}   (expect ({n_val_expect}, 3))  : {val_y_ok}")
    print(f"  nu={train_data.nu}, ny={train_data.ny}  (expect nu=3, ny=3)")

    status_2 = all([train_u_ok, train_y_ok, val_u_ok, val_y_ok])
    print(f"\nCheck 2: {'PASS' if status_2 else 'FAIL'}")

    # ------------------------------------------------------------------
    # Check 3 -- compute_rmse_baseline returns physically reasonable value
    # ------------------------------------------------------------------
    print()
    print("=" * 60)
    print("Check 3: compute_rmse_baseline() on detuned parameters")
    print("=" * 60)

    rmse = compute_rmse_baseline(mat_path)

    # With 2-10% parameter errors on a 0.6m Y sweep, expect RMSE in range
    # of tens of micrometres to a few millimetres.
    # Flag if implausibly small (<1e-6 m, meaning detuning had no effect)
    # or implausibly large (>0.1 m, meaning simulation diverged).
    reasonable = 1e-6 < rmse < 0.1
    print(f"  RMSE = {rmse:.6e} m  ({rmse*1e3:.4f} mm)")
    print(f"  Physically reasonable (1 um -- 100 mm) : {reasonable}")
    status_3 = reasonable
    print(f"\nCheck 3: {'PASS' if status_3 else 'FAIL'}")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print()
    print("=" * 60)
    all_pass = all([status_1, status_2, status_3])
    for label, ok in [
        ("Check 1 (mat file structure)",          status_1),
        ("Check 2 (deepSI System_data shapes)",   status_2),
        ("Check 3 (RMSE_baseline reasonable)",    status_3),
    ]:
        print(f"  {label:<45} {'PASS' if ok else 'FAIL'}")
    print()
    print(f"RMSE_baseline to use in ParameterizedLFRBlock: {rmse:.6e} m")
    print()
    print(f"Overall: {'ALL PASS' if all_pass else 'SOME FAILED'}")
    print("=" * 60)
