"""
gantry_compare.py
-----------------
Compares the Python frozen-LTI simulation output against MATLAB references.

Loads:
    simulations/frozen_lti/y.npz   — Python model output (generated by gantry_sim.py)
    Matlab-output/gantry_q3_lsim.mat    — q3: MATLAB lsim output (linear baseline)
    Matlab-output/gantry_q_simscape.mat — q:  Simscape nonlinear ground truth

Three comparisons (all in metres):
    y  vs q3 — implementation check  (should be near-zero if physics is correct)
    q3 vs q  — linearisation gap     (inherent model error, not our doing)
    y  vs q  — total error            (what the augmentation must learn to correct)

Plots: 3 panels (X1, X2, Y), each with y, q3, q on the same axes.
Prints: RMS and max absolute residual per channel for each comparison.

Run from repo root:
    conda run -n GraduationProject python scripts/gantry/gantry_compare.py
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat


# ------------------------------------------------------------------
# Paths (hardcoded relative to repo root)
# ------------------------------------------------------------------
_repo_root = os.path.join(os.path.dirname(__file__), '..', '..')

_SIM_PATH   = os.path.join(_repo_root, 'simulations', 'frozen_lti', 'y.npz')
_Q3_PATH    = os.path.join(_repo_root, 'Matlab-output', 'gantry_q3_lsim.mat')
_Q_PATH     = os.path.join(_repo_root, 'Matlab-output', 'gantry_q_simscape.mat')

_CHANNEL_LABELS = ['X1 [m]', 'X2 [m]', 'Y [m]']


def _rms(e):
    return np.sqrt(np.mean(e ** 2))


def _print_residuals(label, e):
    """Print RMS and max absolute residual per channel."""
    print(f"  {label}:")
    names = ['X1', 'X2', 'Y ']
    for i, name in enumerate(names):
        print(f"    {name}  RMS={_rms(e[:, i])*1e6:.2f} µm   max={np.max(np.abs(e[:, i]))*1e6:.2f} µm")


def main():
    # ------------------------------------------------------------------
    # Load data
    # ------------------------------------------------------------------
    if not os.path.exists(_SIM_PATH):
        raise FileNotFoundError(
            f"Simulation output not found: {_SIM_PATH}\n"
            "Run gantry_sim.py first."
        )

    sim  = np.load(_SIM_PATH)
    y    = sim['y']   # (N, 3) Python model output
    t    = sim['t']   # (N,)   time vector

    q3_mat = loadmat(_Q3_PATH, squeeze_me=True)
    q3     = q3_mat['q3']   # (N, 3) MATLAB lsim output

    q_mat  = loadmat(_Q_PATH,  squeeze_me=True)
    q      = q_mat['q']     # (N, 3) Simscape nonlinear output

    N = min(len(t), q3.shape[0], q.shape[0])
    y, q3, q, t = y[:N], q3[:N], q[:N], t[:N]

    print(f"Loaded {N} timesteps  ({t[-1]:.3f} s)")

    # ------------------------------------------------------------------
    # Residuals
    # ------------------------------------------------------------------
    e_y_q3  = y  - q3   # implementation check
    e_q3_q  = q3 - q    # linearisation gap
    e_y_q   = y  - q    # total error

    print("\nResiduals (RMS and max absolute, in µm):")
    _print_residuals("y  vs q3  [implementation check]", e_y_q3)
    _print_residuals("q3 vs q   [linearisation gap]   ", e_q3_q)
    _print_residuals("y  vs q   [total error]          ", e_y_q)

    # ------------------------------------------------------------------
    # Plot
    # ------------------------------------------------------------------
    fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    fig.suptitle('Frozen LTI — Python vs MATLAB references', fontsize=13)

    for i, (ax, label) in enumerate(zip(axes, _CHANNEL_LABELS)):
        ax.plot(t, q[:, i],  color='k',      lw=1.2, label='q  (Simscape nonlinear)')
        ax.plot(t, q3[:, i], color='tab:blue', lw=1.0, linestyle='--', label='q3 (MATLAB lsim)')
        ax.plot(t, y[:, i],  color='tab:red',  lw=1.0, linestyle=':',  label='y  (Python model)')
        ax.set_ylabel(label)
        ax.legend(loc='upper right', fontsize=8)
        ax.grid(True, alpha=0.3)

    axes[-1].set_xlabel('Time [s]')
    plt.tight_layout()

    fig_path = os.path.join(_repo_root, 'simulations', 'frozen_lti', 'comparison.png')
    plt.savefig(fig_path, dpi=150)
    print(f"\nPlot saved to: {fig_path}")
    plt.show()


if __name__ == '__main__':
    main()
