%% v1d: open-loop SAME-INPUT comparison, plant with vs without the hidden MSD
%
% Spec + rationale: README.md in this folder, section 8, V1d.
% Jan's Theme A ask taken literally: change ONLY the plant (add the mass), keep
% the excitation identical, and look whether any output acquires a one-sided
% component. Closed-loop records cannot do this (the loop changes the input
% ~100x in-band when the plant changes, d17), so: replay one fixed recorded
% input open-loop through both plants and compare.
%
%   truth    = gantrySystemExtended (8-state, mh_rigid + ma, the function behind
%              the with-MSD Simulink model gantry_additional_state_2025a;
%              lives in Matlab-scripts/Augmentation/)
%   baseline = gantrySystem (6-state, rigid mh_total, kamtin-fp-model, READ ONLY,
%              the function behind gantry_2025a)
%   input    = recorded u_total of the with-MSD record (stage frame), converted
%              to logical forces with P; ZOH at the native 20 kHz
%              % THEORY: u_total is ZOH at 20 kHz (discrete controller), so ZOH
%              % replay is the exact input reconstruction
%   solver   = fixed-step RK4 at the native rate
%              % THEORY: classical 4th-order Runge-Kutta
%
% Sanity anchor (falsifiability): the truth run must reproduce the recorded
% y and delta_a of the same record (d2 established ~1e-7 m on this data). If
% the replay check fails, the comparison is invalid, do not read the rest.
%
% Location per the folder convention (README header): this script lives in
% scripts/gantry/gantry-zero-mean/ like every other verification script; run it
% in MATLAB from this folder (cd here, then v1d_openloop_same_input_msd).
% Outputs: figures -> ./figures/v1d_<record>_*.png, results -> ./data/v1d_results.mat
%
% The training data itself is generated by
% Matlab-scripts/Augmentation/data/generate_trajectory_data.m
% (gtd_config.m parameters, gtd_run_simulation.m Simulink interface).

clear; clc;

%% Configuration
MA_FRAC = 0.10;   % the augmentation data was generated with 0.10 (user-confirmed
                  % 2026-07-07; gtd_config's own default is 0.50, must pass this)
RECORDS = {'T1_standstill_Ym30.mat', 'T8_ysweep_xmix.mat'};
DEC     = 10;     % HEURISTIC: plot decimation only (analysis uses full data)
SEG_SEC = 1.0;    % HEURISTIC: segment length for the SE of the difference mean
N_SIM   = inf;    % samples to simulate (inf = full record; lower for a smoke run)

here = fileparts(mfilename('fullpath'));            % .../scripts/gantry/gantry-zero-mean
root = fileparts(fileparts(fileparts(here)));       % repo root
addpath(fullfile(root, 'Matlab-scripts', 'Augmentation', 'data'));   % gtd_config
cfg  = gtd_config('augmentation', true, MA_FRAC);   % params + addpath (EOM functions)
dataDir = fullfile(root, 'data', 'gantry', 'matlab', 'trajectory', 'augmentation');
figDir  = fullfile(here, 'figures');
datDir  = fullfile(here, 'data');
if ~exist(figDir, 'dir'), mkdir(figDir); end
if ~exist(datDir, 'dir'), mkdir(datDir); end

% capture everything printed below to a text log next to the results
logFile = fullfile(datDir, 'v1d_console.txt');
if exist(logFile, 'file'), delete(logFile); end
diary(logFile);
diaryGuard = onCleanup(@() diary('off'));   % diary closes even if the run errors
fprintf('v1d_openloop_same_input_msd | run started %s | MA_FRAC = %.2f\n', ...
    datestr(now, 'yyyy-mm-dd HH:MM:SS'), MA_FRAC);

ts = cfg.ts;  fs = cfg.fs;

% plant EOMs, parameters frozen from cfg (single source, same as the generator)
f_truth = @(x, u) gantrySystemExtended(u, x, cfg.m1, cfg.m2, cfg.mb, cfg.mh_rigid, ...
    cfg.Lb, cfg.Jb, cfg.Jh, cfg.d, cfg.cg1, cfg.cg2, cfg.cb1, cfg.cb2, cfg.cy, ...
    cfg.kb1, cfg.kb2, cfg.ma, cfg.ka, cfg.ca, cfg.L0);
f_base  = @(x, u) gantrySystem(u, x, cfg.m1, cfg.m2, cfg.mb, cfg.mh, ...
    cfg.Lb, cfg.Jb, cfg.Jh, cfg.d, cfg.cg1, cfg.cg2, cfg.cb1, cfg.cb2, cfg.cy, ...
    cfg.kb1, cfg.kb2);

results = struct();

for ri = 1:numel(RECORDS)
    rec = RECORDS{ri};
    tag = erase(rec, '.mat');
    fprintf('=== %s ===\n', tag);
    dd = load(fullfile(dataDir, rec));           % y, x_logical, u_total, delta_a
    N  = min([size(dd.u_total, 1), size(dd.x_logical, 1), N_SIM]);
    u_log = (cfg.P * dd.u_total(1:N, :)')';      % stage forces -> logical forces
    xl    = dd.x_logical(1:N, :);                % (N,6) recorded logical states
    da    = dd.delta_a(1:N);
    t     = (0:N-1)' * ts;

    % initial conditions from the record (same for both plants on the shared states)
    vda0 = (da(2) - da(1)) / ts;                 % forward-difference vdelta_a seed
    x_t  = [xl(1, 1:3)'; da(1); xl(1, 4:6)'; vda0];   % [X Th Y da dX dTh dY vda]
    x_b  = xl(1, :)';                                 % [X Th Y dX dTh dY]

    % fixed-step RK4, ZOH input
    Xt = zeros(N, 8);  Xb = zeros(N, 6);
    Xt(1, :) = x_t';   Xb(1, :) = x_b';
    tic;
    for k = 1:N-1
        uk = u_log(k, :)';
        k1 = f_truth(x_t, uk);            k1b = f_base(x_b, uk);
        k2 = f_truth(x_t + ts/2*k1, uk);  k2b = f_base(x_b + ts/2*k1b, uk);
        k3 = f_truth(x_t + ts/2*k2, uk);  k3b = f_base(x_b + ts/2*k2b, uk);
        k4 = f_truth(x_t + ts*k3, uk);    k4b = f_base(x_b + ts*k3b, uk);
        x_t = x_t + ts/6 * (k1 + 2*k2 + 2*k3 + k4);
        x_b = x_b + ts/6 * (k1b + 2*k2b + 2*k3b + k4b);
        Xt(k+1, :) = x_t';  Xb(k+1, :) = x_b';
        if mod(k, floor((N-1)/10)) == 0
            fprintf('  %3.0f %%  (%.1f s elapsed)\n', 100*k/(N-1), toc);
        end
    end

    % map truth 8-state onto the shared 6 logical states
    Xt6  = Xt(:, [1:3, 5:7]);
    da_t = Xt(:, 4);

    % ---- sanity anchor: truth replay vs the recorded data ----
    q_stage_sim = (cfg.P' * Xt6(:, 1:3)')';       % stage positions = P^T * logical
    rep_err = q_stage_sim - dd.y(1:N, :);
    rep_rms = sqrt(mean(rep_err.^2, 1));
    da_err_rms = sqrt(mean((da_t - da).^2));
    fprintf('  replay check, truth vs recorded: stage-pos RMS err [X1 X2 Y] = %.2e %.2e %.2e m\n', rep_rms);
    fprintf('  replay check, delta_a RMS err = %.2e m (signal std %.2e)\n', da_err_rms, std(da));
    if max(rep_rms) > 1e-5
        warning('v1d:replay', 'replay error above 1e-5 m: comparison NOT trustworthy, investigate first');
    end

    % ---- the comparison: difference truth minus baseline on the shared states ----
    D = Xt6 - Xb;                                 % (N,6) logical difference
    nseg  = floor(N / round(SEG_SEC * fs));
    seg   = round(SEG_SEC * fs);
    segm  = zeros(nseg, 6);
    for s = 1:nseg
        segm(s, :) = mean(D((s-1)*seg+1 : s*seg, :), 1);
    end
    d_mean  = mean(D(1:nseg*seg, :), 1);
    d_se    = std(segm, 0, 1) / sqrt(nseg);       % THEORY: SE of the mean
    d_slope = zeros(1, 6);                        % ramp detection, LS linear trend
    for c = 1:6
        p = polyfit(t, D(:, c), 1);  d_slope(c) = p(1);
    end

    chan = {'X [m]', 'Theta [rad]', 'Y [m]', 'dX [m/s]', 'dTheta [rad/s]', 'dY [m/s]'};
    fprintf('  difference truth - baseline (same input, open loop):\n');
    fprintf('  %-14s %12s %12s %12s %14s\n', 'channel', 'mean', '2*SE', '|m|/2SE', 'slope [/s]');
    for c = 1:6
        fprintf('  %-14s %12.3e %12.3e %12.2f %14.3e\n', chan{c}, d_mean(c), ...
            2*d_se(c), abs(d_mean(c))/(2*d_se(c)), d_slope(c));
    end

    results.(tag) = struct('d_mean', d_mean, 'd_se', d_se, 'd_slope', d_slope, ...
        'rep_rms', rep_rms, 'da_err_rms', da_err_rms, 'N', N, 'chan', {chan});

    % ---- figures (decimated for plotting only) ----
    ip = 1:DEC:N;  tp = t(ip);
    ttl = sprintf('Same input, open loop: does adding the MSD push anything to one side?  (%s)', tag);

    % positions, logical (top) + stage (bottom), both plants overlaid
    fh = figure('Visible', 'off', 'Position', [50 50 1500 700]);
    q_stage_b = (cfg.P' * Xb(:, 1:3)')';
    lab_top = {'logical X [m]', 'logical Theta [rad]', 'logical Y [m]'};
    lab_bot = {'stage X1 [m]', 'stage X2 [m]', 'stage Y [m]'};
    for c = 1:3
        subplot(2, 3, c); hold on; grid on;
        plot(tp, Xb(ip, c), 'Color', [0.2 0.6 0.2], 'LineWidth', 0.4);
        plot(tp, Xt6(ip, c), 'Color', [0.8 0.1 0.1], 'LineWidth', 0.4);
        yline(mean(Xb(:, c)), '--', 'Color', [0.2 0.6 0.2], 'LineWidth', 1.2);
        yline(mean(Xt6(:, c)), '--', 'Color', [0.8 0.1 0.1], 'LineWidth', 1.2);
        title(lab_top{c}); if c == 3, legend('baseline (no MSD)', 'truth (with MSD)'); end
        subplot(2, 3, 3 + c); hold on; grid on;
        plot(tp, q_stage_b(ip, c), 'Color', [0.2 0.6 0.2], 'LineWidth', 0.4);
        plot(tp, q_stage_sim(ip, c), 'Color', [0.8 0.1 0.1], 'LineWidth', 0.4);
        yline(mean(q_stage_b(:, c)), '--', 'Color', [0.2 0.6 0.2], 'LineWidth', 1.2);
        yline(mean(q_stage_sim(:, c)), '--', 'Color', [0.8 0.1 0.1], 'LineWidth', 1.2);
        title(lab_bot{c}); xlabel('time [s]');
    end
    sgtitle({ttl, 'positions, both plants overlaid, dashed = record mean'});
    exportgraphics(fh, fullfile(figDir, sprintf('v1d_%s_positions.png', tag)), 'Resolution', 150);
    close(fh);

    % velocities, both plants overlaid
    fh = figure('Visible', 'off', 'Position', [50 50 1500 700]);
    for c = 1:3
        subplot(3, 1, c); hold on; grid on;
        plot(tp, Xb(ip, 3 + c), 'Color', [0.2 0.6 0.2], 'LineWidth', 0.4);
        plot(tp, Xt6(ip, 3 + c), 'Color', [0.8 0.1 0.1], 'LineWidth', 0.4);
        yline(mean(Xb(:, 3 + c)), '--', 'Color', [0.2 0.6 0.2], 'LineWidth', 1.2);
        yline(mean(Xt6(:, 3 + c)), '--', 'Color', [0.8 0.1 0.1], 'LineWidth', 1.2);
        title(chan{3 + c}); if c == 1, legend('baseline (no MSD)', 'truth (with MSD)'); end
    end
    xlabel('time [s]');
    sgtitle({ttl, 'logical velocities, both plants overlaid, dashed = record mean'});
    exportgraphics(fh, fullfile(figDir, sprintf('v1d_%s_velocities.png', tag)), 'Resolution', 150);
    close(fh);

    % the difference signal per channel, with mean and slope annotated
    fh = figure('Visible', 'off', 'Position', [50 50 1500 800]);
    for c = 1:6
        subplot(2, 3, c); hold on; grid on;
        plot(tp, D(ip, c), 'Color', [0.3 0.3 0.7], 'LineWidth', 0.4);
        yline(0, 'k-');
        yline(d_mean(c), '--', 'Color', [0.8 0.1 0.1], 'LineWidth', 1.2);
        title(sprintf('diff %s', chan{c}));
        text(0.02, 0.04, sprintf('mean %+.2e | slope %+.2e /s', d_mean(c), d_slope(c)), ...
            'Units', 'normalized', 'FontSize', 7, 'BackgroundColor', [1 1 1 0.75]);
        if c > 3, xlabel('time [s]'); end
    end
    sgtitle({ttl, 'difference truth minus baseline: a one-sided MSD effect = offset or ramp here'});
    exportgraphics(fh, fullfile(figDir, sprintf('v1d_%s_difference.png', tag)), 'Resolution', 150);
    close(fh);

    % replay check: truth run vs recorded data (the validity anchor)
    fh = figure('Visible', 'off', 'Position', [50 50 1500 800]);
    lab_rep = {'X1', 'X2', 'Y'};
    for c = 1:3
        subplot(4, 1, c); hold on; grid on;
        plot(tp, rep_err(ip, c), 'Color', [0.3 0.3 0.7], 'LineWidth', 0.4);
        yline(0, 'k-');
        title(sprintf('replay error, stage %s [m], RMS %.2e', lab_rep{c}, rep_rms(c)));
    end
    subplot(4, 1, 4); hold on; grid on;
    plot(tp, da(ip), 'Color', [0.2 0.6 0.2], 'LineWidth', 0.4);
    plot(tp, da_t(ip), 'Color', [0.8 0.1 0.1], 'LineWidth', 0.4);
    legend('recorded delta\_a', 'open-loop replay');
    title(sprintf('delta_a, recorded vs replay, RMS err %.2e m', da_err_rms));
    xlabel('time [s]');
    sgtitle({ttl, 'validity anchor: the truth plant must reproduce the recorded data'});
    exportgraphics(fh, fullfile(figDir, sprintf('v1d_%s_replaycheck.png', tag)), 'Resolution', 150);
    close(fh);
    fprintf('  figures written to %s\n', figDir);
end

save(fullfile(datDir, 'v1d_results.mat'), '-struct', 'results');
fprintf('results saved to %s\n', fullfile(datDir, 'v1d_results.mat'));
fprintf('console log saved to %s\n', logFile);
diary off;
